### ISSUE TITLE
Preprocess and process are too verbose and causing notebooks to stop responding

### ISSUE THREAD

**Issue by nd2506** [paninski-lab/yass#103]
Need to remove some logging details out.

**Comment by edublancas** [comment]
Do you have your logger configured to DEBUG?

Changing to INFO or ERROR makes it less verbose, that's the advantage of using logging, we can control how verbose it is, please do not remove logging statements

```python
import logging
logging.basicConfig(level=logging.ERROR)
```

**Comment by nd2506** [comment]
ok thanks
