### ISSUE TITLE
Function to run entire pipeline using dictionary.

### ISSUE THREAD

**Issue by hooshmandshr** [paninski-lab/yass#108]
We'd like to have an internal function that calls the entire pipeline given a configuration dictionary.

**Comment by edublancas** [comment]
Currently working on it

**Comment by edublancas** [comment]
Just pushed changes, function is on `src/pipeline.py`, almost parameters as the old `_run_pipeline` that you were using, just removed `output_file` since we were not using it

**Comment by edublancas** [comment]
Sorry, didn't realize I partially fixed this: there is a function to call the pipeline but I didn't implement the dictionary part. Re-opening this issue

**Comment by edublancas** [comment]
Fixed
