### ISSUE TITLE
error in pipeline.py

### ISSUE THREAD

**Issue by jinhyunglee** [paninski-lab/yass#113]
I got an error saying
`  File "/ssd/data/peter/yass/src/yass/pipeline.py", line 61, in run
    logging.config.dictConfig(logging_config)`

seems like it gets fixed after adding 
`import logging.config`

what do you guys think?

**Comment by edublancas** [comment]
What's the error message?

**Comment by jinhyunglee** [comment]
sorry, message got cut.
here it is
`AttributeError: module 'logging' has no attribute 'config'`

**Comment by jinhyunglee** [comment]
I got another error:
`  File "/ssd/data/peter/yass/src/yass/pipeline.py", line 88, in run
    shutil.copy2(config, path_to_config_copy)
  File "/home/peter/miniconda3/envs/peter/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/peter/miniconda3/envs/peter/lib/python3.6/shutil.py", line 103, in copyfile
    if _samefile(src, dst):
  File "/home/peter/miniconda3/envs/peter/lib/python3.6/shutil.py", line 88, in _samefile
    return os.path.samefile(src, dst)
  File "/home/peter/miniconda3/envs/peter/lib/python3.6/genericpath.py", line 96, in samefile
    s1 = os.stat(f1)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not dict
`

**Comment by jinhyunglee** [comment]
also, `return spike_train` is inside of `if complete:` statement, is it intended?

**Comment by calvinytong** [comment]
Original error is explained by [this](https://stackoverflow.com/questions/2234982/why-both-import-logging-and-import-logging-config-are-needed). Not sure about the second error, seems like some kind of file manipulation error.

**Comment by edublancas** [comment]
It is right to do the `import logging.config` to fix the first error, and I know what's the problem with the second one, I can fix it

**Comment by jinhyunglee** [comment]
thanks all.
I though some tests use pipeline.py
I am wondering how it passed..

**Comment by edublancas** [comment]
It passed because I didn't test the function when passing a dictionary (instead of the path to the config file), I'm adding the test

**Comment by jinhyunglee** [comment]
thanks! i am getting used to this way of communication now. its great

**Comment by edublancas** [comment]
Forgot to mention: return spike_train, shouldn't be inside the if statement, will move it out
