### ISSUE TITLE
End-to-end evaluation

### ISSUE THREAD

**Issue by hooshmandshr** [paninski-lab/yass#117]
Expand evaluation to produce metrics for all parts of the pipeline.
 - Add some evaluation classes to yass/src/evaluate
 - Add standard visualization classes to yass/tests/evaluate. Move all the plotting/visualizations to yass/src/evaluate
 - Modify the yass/tests/evaluate automatic scripts so that it produces metrics on triage, spike detection, clustering, deconvolution and final stability and accuracy results given a standard config file.

**Comment by calvinytong** [comment]
As discussed this should also include a notebook that plots these results to be run as a scheduled job on our server.

**Comment by calvinytong** [comment]
status on this? is this closeable now?

**Comment by hooshmandshr** [comment]
Yep. There is a notebook in the examples/evaluation.

There are two type of plots here (outlined in the notebook). One type (accuracy and stability) is one per data set. The other type is more of an interactive visualization with many possible options (i.e. comparisons among several particular clusters/units). The necessary data for this saved in temp directories but plots can not be exhaustively generated ahead of time.
