### ISSUE TITLE
Automatic detection and setting of GPU and CPU memory 

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#128]
1. Two default max_memory setting should be implemented.

2. Additionally, yass should not crash half-way through if memory isn't sufficient. Memory can be checked prior to run and warn user if CPU or GPU total and/or free memory is too low. Memory should then be lowered to the max reasonable to run sort.

3. For those who have tensorflow-GPU installed that wish to run CPU mode only there's a command line option that can be run: 

export CUDA_VISIBLE_DEVICES=

Lots of tools to read memory, e.g.:
https://stackoverflow.com/questions/22102999/get-total-physical-memory-in-python

**Comment by edublancas** [comment]
I'll work on this

**Comment by calvinytong** [comment]
@catubc this issue has 3 units of work that can be separated and it looks like some of them are complete. Could we update/split it into single units of work?

**Comment by edublancas** [comment]
Yes, let's split this into several parts
