### ISSUE TITLE
Spike indexes (events) too close to start/end of recording - can cause crash

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#130]
Re: preprocess.run(): waveform extraction step:

            # TODO: what should the behaviour be for spike indexes that are
            # when starting/ending the recordings and it is not possible to
            # draw a complete waveform?

Cat: Yes, events too close to end/start of recording will lead to crash during preprocessing (possibly other places). This has happened to me using simulated datasets.

Suggested solution for preprocessing: completely ignore such events - there will be very few such events. 

Also for neural network training - such gold-standard / ground-truth events should also be ignored (for now).

**Comment by edublancas** [comment]
I actually removed that TODO tag a while ago, we are removing those events.
