### ISSUE TITLE
Yass (should not) automatically install tensorflow 

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#131]
So I noticed on pip install that the yass pkg installs tensorflow (as native?!).

Is this going to overwrite native tensorflow installations on people's machines including -gpu off/on flags and special compiled instructions (e.g. AVX)?

**Comment by edublancas** [comment]
Right, we should remove it. Thanks for pointing this out

**Comment by calvinytong** [comment]
Are we sure we want to remove it? It is required for the package to run, so I'd be inclined to leave it in somehow. Not sure how this is usually done.

**Comment by hooshmandshr** [comment]
I think the vanilla tensorflow that is installed automatically will not cause an issue I think. Even if updated it will no affect existing tensorflow-gpu package.
For the users to enjoy GPU they should install it according to instructions of TF itself (i.e. nvidia libraries and cuda libraries and setting up environment variables).

**Comment by edublancas** [comment]
I think the best is to check how other libraries that depend on tensorflow (e.g. keras) do it and follow best practices, can you help with this @calvinytong?

**Comment by catubc** [comment]
My original point is that tensorflow should not overwrite native installations. For example, it took me a few days to figure out how to compile tensorflow correctly from source using special processor options. 

There's a way to determine this and avoid it. Obviously if tensorflow doesn't exist it can be installed... but  some users might use native environments (like me) and they may complain if they loose their tf installation (which may have been done by someone else for them with more knowledge!).

**Comment by calvinytong** [comment]
Wel I think Keras is weird because it doesn't depend on a backend, so it's not really a strict depends. Funny enough the Blei lab opened an issue on tensorflow with this exact [question](https://github.com/tensorflow/tensorflow/issues/7166). The solution is just to use the optional requirements. As noted in the issue, not ideal, but should work for now.
