### ISSUE TITLE
Implementing an intermediate save-step after run_detect_triage_featurize

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#136]
On a long run I got a crash shortly after this step (see issue #135 for full error log):

yass.batch.batch@multi_channel_apply 17/02/2018 00:53:07 INFO yass.neuralnetwork.apply.run_detect_triage_featurize took 1.0 hours 41.0 minutes 56.27954912185669 seconds

But when I ran again - this step was being recomputed. 

**Suggestion**: would be good to save the output of this processing step to avoid running it again.

**Comment by edublancas** [comment]
Yes, we are saving partial results to avoid these issues, we implemented that in the preprocessor but not yet in the processor

**Comment by catubc** [comment]
Closing for now, I think intermediate step saving is a system-wide issue that is being slowly addressed.
