### ISSUE TITLE
sample configuration file is changed

### ISSUE THREAD

**Issue by jinhyunglee** [paninski-lab/yass#150]
@edublancas, can you put config file back to the version before merging integration test? 
https://github.com/paninski-lab/yass/blob/master/examples/config_sample.yaml

**Comment by edublancas** [comment]
I changed it because with the old one the test was broken, what's the problem?

**Comment by jinhyunglee** [comment]
one thing I noticed is that default value for nn triage is changed to 0.9.
let me see if there is other things that need to be fixed

**Comment by jinhyunglee** [comment]
the test failed because of the same issue as in #94.

removing
`location:
  isolation_threshold: 0`
and `threshold_collision: 0.5`

should be good
