### ISSUE TITLE
Error after refactored preprocess

### ISSUE THREAD

**Issue by jinhyunglee** [paninski-lab/yass#151]
After splitting preprocessor into two,

some of the changes are reverted.

For example, 
https://github.com/paninski-lab/yass/blob/ffa550950bd38ec82cef7cfd6606b5f15f98953d/src/yass/preprocess/run.py#L376

I changed the preprocess/run.py to reflect the changes in neural net code (splitting detector and auto encoder) as above.

but this change is gone now.

**Comment by edublancas** [comment]
Do you know the hash of the commit so I can update the changes?

**Comment by jinhyunglee** [comment]
what is hash of the commit? 
`ffa5509` this one?

**Comment by edublancas** [comment]
Yes

**Comment by jinhyunglee** [comment]
how about just copy and paste the code in the link that I posted to detect/run.py?

**Comment by edublancas** [comment]
This is a testing coverage problem, the build shouldn't pass. let me add more tests

**Comment by edublancas** [comment]
One comment.

You are setting NNAE in two places

https://github.com/paninski-lab/yass/blob/ffa550950bd38ec82cef7cfd6606b5f15f98953d/src/yass/preprocess/run.py#L359

https://github.com/paninski-lab/yass/blob/ffa550950bd38ec82cef7cfd6606b5f15f98953d/src/yass/preprocess/run.py#L409

Seems redundant. Can we remove the second one?

**Comment by jinhyunglee** [comment]
Yes. It is redundant

**Comment by edublancas** [comment]
Ok, will remove it
