### ISSUE TITLE
yass.templates.run@run - replace memmap in template step with low-memory batch version

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#157]
Latest yass fix from @nd2506  (Tuesday 20th, morning) works but memmap at template stage is still taking up too much memory (e.g. 60GB+ and counting) during processing.

...
yass.cluster.util@run_cluster_loccation 20/02/2018 11:38:21 INFO Processing channel 509
yass.cluster.util@run_cluster_loccation 20/02/2018 11:38:23 INFO Processing channel 510
yass.cluster.util@run_cluster_loccation 20/02/2018 11:38:23 INFO Processing channel 511
yass.cluster.run@run 20/02/2018 11:38:25 INFO Mainprocess done in 541 seconds.
yass.cluster.run@run 20/02/2018 11:38:25 INFO 	triage:	185.956788 seconds
yass.cluster.run@run 20/02/2018 11:38:25 INFO 	coreset:	0 seconds
yass.cluster.run@run 20/02/2018 11:38:25 INFO 	masking:	0 seconds
yass.cluster.run@run 20/02/2018 11:38:25 INFO 	clustering:	290.262555 seconds
**yass.templates.run@run 20/02/2018 11:38:25 INFO Getting Templates...**

**Comment by jinhyunglee** [comment]
I went through the codes.
It computes waveforms for all spikes first and then calculates mean.

This won't scale.
@edublancas, 
Let me work on replacing this with multi channel batch processor.
I will work on replacing all memory map related parts with multi channel batch processor today.

**Comment by catubc** [comment]
Ok, my memory has filled up to 180GB and counting...

**Comment by jinhyunglee** [comment]
Luckily, there are only two places where we are reading data without using multichannel batch processor.

1. score in threshold/dimension_reduction.py
2. get_templates in templates/util.py

I will fix them today. Let me know if you find any other such places

**Comment by catubc** [comment]
Here's the function that I replaced it with:

```
def _compute_templates(self):
        """Compute templates from spike train

        Returns
        -------
        numpy.ndarray
            [n_channels, n_features, n_templates] array with the templates
        numpy.ndarray
            1D array with the number of spikes used to form the ith template
        """
        # get waveforms
	templates = []
	weights = []
	for single_id in self.all_ids:
	    #waveforms = [self.waveforms_for_group(id_) for id_ in self.all_ids]
	    waveform = [self.waveforms_for_group(single_id)]

	    self.logger.debug('Loaded {:,} waveforms for single_id'.format(len(waveform)))

	    # compute templates for every group
	    template = [np.mean(waveform, axis=0)]
	    templates.append(template)

	    # get weights (number of waveforms used to compute each template)
	    weight = np.array([len(waveform)])
	    weights.append(weight)
	    
	# stack
	templates = np.stack(templates, axis=2)

        self.logger.debug('Finished computing templates, shape is: {}'
                          .format(templates.shape))

        # return transposed templates (makes plotting easier) and weights
        return templates.transpose(1, 0, 2), weights
```

**Comment by catubc** [comment]
Something is still not right at this loop. The code loaded about 8GB of data just for a single id, and it's taking >1 minute per id to load


yass.cluster.util@run_cluster_loccation 20/02/2018 13:41:47 INFO Processing channel 510
yass.cluster.util@run_cluster_loccation 20/02/2018 13:41:47 INFO Processing channel 511
yass.cluster.run@run 20/02/2018 13:41:50 INFO Mainprocess done in 531 seconds.
yass.cluster.run@run 20/02/2018 13:41:50 INFO 	triage:	183.072049 seconds
yass.cluster.run@run 20/02/2018 13:41:50 INFO 	coreset:	0 seconds
yass.cluster.run@run 20/02/2018 13:41:50 INFO 	masking:	0 seconds
yass.cluster.run@run 20/02/2018 13:41:50 INFO 	clustering:	280.823561 seconds
yass.templates.run@run 20/02/2018 13:41:50 INFO Getting Templates...
yass.explore.explorers@_compute_templates 20/02/2018 13:43:09 DEBUG Loaded 1 waveforms for single_id
yass.explore.explorers@_compute_templates 20/02/2018 13:44:24 DEBUG Loaded 1 waveforms for single_id

**Comment by catubc** [comment]
This issue being addressed already.
