### ISSUE TITLE
Config validator error messages should be more verbose

### ISSUE THREAD

**Issue by calvinytong** [paninski-lab/yass#159]
Currently, when an item is missing from the config, yass returns a key error. This key error is only thrown when the algorithm reaches that stage. Thus, it is hard to tell when there is an error in the code or just an error in the config. This error handling can be improved if

- [ ] Validation of the YAML file occurs before any processing

- [ ] The validator error messages are made more verbose by listing what section the missing parameter is in and what the parameter does

**Comment by edublancas** [comment]
I am aware of these issues, haven't found type to improve the validator. Can you work on this?

**Comment by calvinytong** [comment]
I'll look for some kind of YAML Schema system to solve this

**Comment by calvinytong** [comment]
I think [this](https://github.com/23andMe/Yamale) is a good option. @jinhyunglee do you think you could help me create the yaml template to validate? I'm not exactly sure what all of the options are.

**Comment by edublancas** [comment]
related to #73

**Comment by edublancas** [comment]
I started working on this
