### ISSUE TITLE
travis should break when docs fail to build

### ISSUE THREAD

**Issue by edublancas** [paninski-lab/yass#165]

**Comment by calvinytong** [comment]
I would recommend creating a `make docs` target and just adding that to the build. It is a useful functionality to have

**Comment by calvinytong** [comment]
Oh, I see that is already there. We need to add a flag to that command to have it hard fail. I'll look into this.

**Comment by edublancas** [comment]
I did it, but I think there is some misconfiguration with the docs building service (readthedocs)

**Comment by calvinytong** [comment]
I thought read the docs was the hosting service

**Comment by edublancas** [comment]
It's both, they build it and they host it. im not sure if we can get a notification from them if the build has some errors, that's why i wanted to also build the docs on travis, we are running the same process so it should throw the same result every time
