### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by edublancas** [paninski-lab/yass#167]
Given that we are now working on making this faster for large datasets, it may be good to have a way to test computing performance. Ideas?

**Comment by calvinytong** [comment]
There are many ways to test performance, which depend on what you are trying to optimize for. I think we need a better idea of what we are testing for to answer this question.

**Comment by edublancas** [comment]
I think we want to measure: time and memory

**Comment by calvinytong** [comment]
Okay, so for time I think we do okay with logging for now. We can use a profiler for identifying more fine-grained things. For memory, we can use the [psutil](https://pypi.python.org/pypi/psutil) library although in my experience it is a bit laggy. We can also profile memory usage after the fact.
