### ISSUE TITLE
Butterfilter should use filtfilt instead of lfilter

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#175]
I think that filtfilt is generally as it is a zero-phase filter, see the nice plots here:

https://dsp.stackexchange.com/questions/19084/applying-filter-in-scipy-signal-use-lfilter-or-filtfilt

**Comment by catubc** [comment]
From martin spacek code: 
```

    if causal:
        data = scipy.signal.lfilter(b, a, data) # causal, adds freq-dependent phase lag
    else:
        data = scipy.signal.filtfilt(b, a, data) # non-causal, 0 phase lag

```

**Comment by edublancas** [comment]
changed in #229
