### ISSUE TITLE
saving progress does not function correctly

### ISSUE THREAD

**Issue by hooshmandshr** [paninski-lab/yass#180]
If for some reason (e.g. max memory error) yass crashes filtered.bin is saved but filtered.yaml is not. And rerunning yass will crash because of this.
This is not a major problem since you can just delete yass.bin and things go back to normal.

**Comment by catubc** [comment]
Duplicate with issue #179. 
Can close this.

**Comment by hooshmandshr** [comment]
Thanks. Closed it.
