### ISSUE TITLE
Dealing with memory issues

### ISSUE THREAD

**Issue by edublancas** [paninski-lab/yass#205]
Taking pat of the discussion from #128 here...

1. Additionally, yass should not crash half-way through if memory isn't sufficient. Memory can be checked prior to run and warn user if CPU or GPU total and/or free memory is too low. Memory should then be lowered to the max reasonable to run sort.

2. For those who have tensorflow-GPU installed that wish to run CPU mode only there's a command line option that can be run:

About 1: we can come up with some rules of thumb for this, we can measure the memory overhead we are adding and set the maximum memory accordingly, not sure if this is the best approach. Comments?

About 2: Sounds like we should leave this to the end user. We just run tensorflow with the default device, if it's GPU/CPU doesn't matter to us. The only thing we care about is setting the right max_memory parameter (see #204)

**Comment by catubc** [comment]
Re: 1, actually maybe we should wait a bit until you've figured out some rules from memory profiler. Perhaps we should also put the burdern on end-user to manage some of this, but they may get annoyed if half way through they get a memory crash cause they didn't know how much memory yass would take up.

Re: 2, agreed, probably should just leave as is and document command line options somewhere.
