### ISSUE TITLE
Pipeline spins up many instances of the same FrozenJSON

### ISSUE THREAD

**Issue by calvinytong** [paninski-lab/yass#206]
[This](https://github.com/paninski-lab/yass/blob/master/src/yass/config/config.py#L48) line is called many times during the integration test and causes travis to fail. For now, it has been commented out, but we should get to the bottom of the issue.

**Comment by edublancas** [comment]
Fixed the problem, FrozenJSON builds recursively, that's the reason why we were seeing too many log lines.
