### ISSUE TITLE
Rename MFM.py to mfm.py

### ISSUE THREAD

**Issue by neil-gallagher** [paninski-lab/yass#214]
When running YASS for the first time after installing I received the error " ModuleNotFoundError: No module named 'yass.mfm' "
I'm running version 0.7, which was installed in an anaconda environment using " pip install yass-algorithm "
For now, it appears renaming the MFM.py file to mfm.py fixes the issue.

**Comment by edublancas** [comment]
Thanks for reporting this. I was able to reproduce the error, will fix it soon. In the meantime renaming the file works, installing directly from the repo should also work: `pip install git+git://github.com/paninski-lab/yass@0.7`

**Comment by edublancas** [comment]
Just released a new version `0.8` which fixes the problem, thanks for reporting.
