### ISSUE TITLE
bug in yass.threshold.detect

### ISSUE THREAD

**Issue by decarlson** [paninski-lab/yass#239]
Lines 159-160 state:

>     # FIXME: is this a safe thing to do?
    index = np.zeros((1000000, 2), 'int32')

I can confirm that it is not...

**Comment by decarlson** [comment]
Yep, that's all.  I fixed it for me by just making it larger, but that's not a good long term solution.

**Comment by edublancas** [comment]
Ok, I'll work on this

**Comment by catubc** [comment]
Well, I guess I was right to be suspicious of this. The solution is to make an empty index array

index = np.zeros((0,2),'int32')
and to then constantly append to it:

index = np.concatenate((index, spt_c[idx_keep])) 

or somthing close to this.

let me know if you have questions.
