### ISSUE TITLE
Clarification in misaligned spikes function

### ISSUE THREAD

**Issue by edublancas** [paninski-lab/yass#242]
The `misaligned_spikes` function returns two arrays named `x_misaligned` and `x_misaligned2`:

https://github.com/paninski-lab/yass/blob/a064d4b23434c4083f875da49744ad8fc3828e08/src/yass/augment/make.py#L84

Judging by the docstring seems like they correspond to temporally and spatially misaligned spikes, in that order. I renamed the variables to make them clear. Please confirm if the assumption is correct:

https://github.com/paninski-lab/yass/blob/0a16b5d7f390d48178a5d89b5edfc9fb5feb7217/src/yass/augment/util.py#L77

**Comment by jinhyunglee** [comment]
Based on the code, what you said is correct 

But did someone make changes in code?
If I remember correctly, one of them is supposed to be both temporal and spatial misalignment and another one is supposed to be just temporal misalignment.

**Comment by edublancas** [comment]
I haven't made any changes (besides renaming variables and re-organizing code), this is the version we have in the master branch (same file as above):

https://github.com/paninski-lab/yass/blob/a064d4b23434c4083f875da49744ad8fc3828e08/src/yass/augment/make.py#L84

**Comment by jinhyunglee** [comment]
Looking at code here:
https://github.com/paninski-lab/yass/blob/32343dd174e240ac18fe00d65c0077715b42c272/src/yass/augment/make.py

there is no misalignment2 ?

**Comment by jinhyunglee** [comment]
maybe @ShenghaoWu made changes?

**Comment by edublancas** [comment]
The one you posted is an old version, the latest one in master has misaligned2:

https://github.com/paninski-lab/yass/blob/a064d4b23434c4083f875da49744ad8fc3828e08/src/yass/augment/make.py#L133

Which is the one I'm using.

**Comment by jinhyunglee** [comment]
That is the change made after I left. Maybe better to ask @ShenghaoWu then.

**Comment by jinhyunglee** [comment]
By the way, I strongly disagree with having spatial only misalignment in there.
I will confuse NN so much

**Comment by edublancas** [comment]
Yeah, we are having trouble with the triage network. Seems like the problem is in the training data, I am getting familiar with the code in augment/. would be good if you have time to talk in the next few days. Will let you know once I have specific questions.

**Comment by ShenghaoWu** [comment]
misaligned: both spatially and temporally misaligned data; it is used for training detect NN only.
misaligned2: only spatially misaligned data; it is used for training triage NN only.
@jinhyunglee  could you comment a bit on why misaligned2 will confuse triage NN (it seems that when using the old version (no misaligned2 for triage data) the result is better. If spatially-only misaligned data is wrong I can change it into temporally-only misaligned data for training triage NN.

**Comment by ShenghaoWu** [comment]
@edublancas  as of now your x_temporally should be x_temporally_spatially and x_spatially is still x_spatially. But we may want to remove/change x_spatially as Peter pointed out it may confuse the NN.

**Comment by jinhyunglee** [comment]
@ShenghaoWu 
having space only misaligned data means is the same as doing spatial alignment. We've had experience that doing spatial alignment using NN does not work well.

**Comment by ShenghaoWu** [comment]
I see, thanks!
