### ISSUE TITLE
Run Yass with lower GPU memory

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#243]
Would be good to have an option where GPU only loads during detect stage and then unloads.  Or loads with less memory.

For example, would it be possible to run 2 x yass instances so that one can be used to debug while another is running?

**Comment by edublancas** [comment]
Fixed (code already in master), there are two ways to do this. @catubc @nd2506 

When running yass from a Python session:

```python
import yass

# this needs to run before any other yass/tensorflow code
# other settings can also be set here
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.5
yass.set_tensorflow_config(config=config)
```

From the command line:

```shell
# use up to 50% of total GPU memory
yass sort config.yaml --global_gpu_memory 0.5
```
