### ISSUE TITLE
Conda installation instructions

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#257]
### 0.  Optional: install libcudnn and cuda that are compatible with tensorflow-gpu libraries
- download libcudnn7_7.1.4.18-1+cuda9.0_amd64.deb
- cd download directory
sudo dpkg --install libcudnn7_7.1.4.18-1+cuda9.0_amd64.deb

### 1.  Create virtual environment to run yass (Strongly recommended to use virtual environments)
conda create --name yass python=3.6
conda activate yass

### 2.  From yass virtual environment
conda install -c anaconda tensorflow-gpu (OR conda install -c conda-forge tensorflow if you don't have GPU)
conda install -c anaconda statsmodels (OR pip install statsmodels)
conda install -c conda-forge matplotlib 
conda install -c anaconda networkx (OR pip install networkx)
conda install -c pytorch pytorch 
conda install -c anaconda cython (OR pip install cython)
pip install git+https://github.com/paninski-lab/diptest@fix-import

### 3.  Move to root directory where you want yass installed
git clone -b dev https://github.com/paninski-lab/yass  (this will install development version)
cd yass
pip install .

**Comment by calvinytong** [comment]
It might be easier to just bundle this stuff in the make install target

**Comment by catubc** [comment]
Yes, good idea. Just have to make sure we tested it thoroughly and make sure cudnn doesn't conflict with tensorflow (which it might).

**Comment by edublancas** [comment]
It isn't trivial to create a script to setup everything from scratch (cuda + python env), since it completely depends on the user's OS. I would leave CUDA setup on the user's behalf. Setting up python is not that hard if we use conda, but again, some user may not want to use conda but other virtual environment tool.

I think it's better to just provide scripts with sample setup and let the details to the user

**Comment by catubc** [comment]
We must provide installation instructions that are foolproof even if they involve conda as we can't assume endusers will automatically know how to do this.  If endusers want to use native or other environments, that will be up to them, but we need to make sure if someone follows our install instructions everything will work.

**Comment by edublancas** [comment]
If we really want to do this, we can provide a virtual machine with everything setup

**Comment by catubc** [comment]
Sure, whatever is best... I just though conda was the easiest instructions to follow.
