### ISSUE TITLE
Bug in clustering global_merge_all_ks

### ISSUE THREAD

**Issue by edublancas** [paninski-lab/yass#258]
I found a bug and want to make sure my solution is ok, the current code in cat-parallel5 looks like this:

https://github.com/paninski-lab/yass/blob/bf5eab744e27dfc4d3766f3a7d3dd2f43088d59e/src/yass/cluster/util.py#L1871

It iterates over every channel, but for small recordings it is possible that not all channels generated files (i am not entirely sure how these files are generated), so instead of looping over channels i am looping over actual files in that directory:

```python
filenames = [f for f in os.listdir(chunk_dir) if f.endswith('.npz')]

        for filename in filenames:
            path_to_file = os.path.join(chunk_dir, filename)

            logger.info('loading %s', path_to_file)
            data = np.load(path_to_file)
```

**Comment by catubc** [comment]
So this is not the optimal solution, you can't loop over files in a directory because there may be others as well.  

You should loop over channels but check if file exists first.  So I'd leave the code as is and add this modification:

`for channel in range(CONFIG.recordings.n_channels):
            fname = chunk_dir+'/channel_{}.npz'.format(channel)
            if os.path.exists(fname)==False: continue
            data = np.load(fname)
....
`

**Comment by edublancas** [comment]
Ok, I'll fix it
