### ISSUE TITLE
Loging and meta-data tracking

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#260]
1.  Currently yass saves progress files for chunks/segments for each stage of processing so that crashes or interruptions can be recovered.  However, CONFIG params can change on restart and cause incorrect results.   We need to add important meta data to the progress files to warn user that parameters have changed and either old files need to be deleted or changed.

2.  We need to start moving a lot of the verbose comments to proper logger using available tools.  This way all runtime information should be logged even if end users turns off verbose options.

**Comment by edublancas** [comment]
I am already saving a copy of the config file when a user runs the pipeline, we can check this to make sure there hasn't been any changes

**Comment by catubc** [comment]
Yes, that's great, but should probably move all print() statements to logging.  

Issue 1 is more involved, do you have any suggestions?

**Comment by edublancas** [comment]
Issue 1 is what I mentioned about the config. Every time the user runs the pipeline I copy contents of config.yaml and put it in the tmp/ folder. we can always check that the config.yaml is still the same

**Comment by catubc** [comment]
I see, great.  So how do we implement a checker like that?

**Comment by edublancas** [comment]
I can work on this tomorrow
