### ISSUE TITLE
YASS_TESTING_DATA_URL?

### ISSUE THREAD

**Issue by magland** [paninski-lab/yass#261]
Trying to run test example. I see you no longer distribute the test data in the repo. Are we supposed to run the `./scripts/download_test_data` script? It seems it requires a YASS_TESTING_DATA_URL variable to be set.

**Comment by edublancas** [comment]
That's correct. We are currently updating our testing suite to test the package with the a dataset that we cannot share.

We are planning to add the public testing dataset again but we have to make some changes. So, unfortunately, the examples cannot be run for now

**Comment by magland** [comment]
Thanks for the reply. Do you have some kind of minimal python example that does not require downloading a dataset? Or do you have some basic instructions for if I have my own dataset?

**Comment by catubc** [comment]
Hey Jeremy.  Both master and the most recent dev branch I work on (yass-cat-parallel5) should work. 
 The data structure is a raw binary ('int16' in python) in time order (i.e. ch0 time0, ch1 time0... ) and the  site geometry is a column wise x and y coords (no commas) like this:

-585.0 270.0 
-645.0 270.0 
-525.0 270.0 
-615.0 210.0 
-555.0 210.0 
...
Additionally you will need the .yaml config file that matches the version of yass you would run. 

However, as Edublancas mentioned, we are undergoing substantial changes and there are major updates still to go...
