### ISSUE TITLE
Environment Variables required at runtime

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#265]
So we'll need to somehow pass these variables at starttime: 

export GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
#export CUDA_VISIBLE_DEVICES=

The last one is optional for turning off GPU in case it's problematic for enduser.

**Comment by edublancas** [comment]
What is the first variable for? looks platform-specific
