### ISSUE TITLE
implement YASS on SpikeInterface

### ISSUE THREAD

**Issue by alejoe91** [paninski-lab/yass#288]
Hi YASS team!

We wanted to ask you if you can implement YASS in the SpikeInterface project (https://github.com/SpikeInterface), which is the engine behind SpikeForest.

With @magland we are merging the SpikeForest and SpikeInterface implementation, so that SpikeForest will call the SpikeInterface sorter wrappers, which will only be maintained in one place.

The sorter wrappers are in this repo: https://github.com/SpikeInterface/spikesorters and I made an issue for the YASS implementation (https://github.com/SpikeInterface/spikesorters/issues/11).

Please let us know how we can help for the implementation. There should be plenty of examples among the other implemented wrappers.

Cheers
Alessio & the SpikeInterface Team

**Comment by jinhyunglee** [comment]
Hello Alessio!

thank you for letting us know.
Samuel guided me on what I need to do the implementation.
Once YASS is ready, I will do the work. 

Talk to you soon. I will keep it open!

**Comment by alejoe91** [comment]
Hi @jinhyunglee 

Congrats on the new preprint! Do you think we could include a wrapper in SpikeInterface now?

Let me know!
Cheers,
Alessio

**Comment by catubc** [comment]
Hi Alessio. You should be able to get it to install, most users have been able to follow instructions, let us know if you have trouble.

**Comment by jinhyunglee** [comment]
Hi @alejoe91,

thanks. as @catubc mentioned, you should be able to install following the instruction.
But please do let us know if something is not clear.

**Comment by alejoe91** [comment]
Hi guys,

I don't know when I'll have time to do it, but I can give it a try. If you have time during this quarantine situation and want to make the wrapper you are welcome. It's quite straight forward and there are plenty of examples (see the [klusta](https://github.com/SpikeInterface/spikesorters/tree/master/spikesorters/klusta) wrapper for an example of a CLI spike sorter).

Can you provide a ilst of sensitive parameters that you would like to expose?

**Comment by alejoe91** [comment]
> Hello Alessio!
> 
> thank you for letting us know.
> Samuel guided me on what I need to do the implementation.
> Once YASS is ready, I will do the work.
> 
> Talk to you soon. I will keep it open!

@jinhyunglee I remember you said you would do the work eheheheh

**Comment by alejoe91** [comment]
Hi @catubc and @jinhyunglee 

We are going to make a new stable release of SpikeInterface in about one week. Let us know if you have time to include a YASS wrapper. 

Cheers
Alessio

**Comment by catubc** [comment]
Hi Alessio, we can certainly help.  Please email me directly (mitelutco@gmail.com).
