### ISSUE TITLE
stuck in the clustering process

### ISSUE THREAD

**Issue by pplenck** [paninski-lab/yass#290]
HI Guys
I am running into an issue I can't figure out. I'd love to use yass but I am stuck here, and no-one can help. Even engineers in the lab.

In the cluster.run part, yass is stuck in the following part:

INFO:yass.cluster.util:Processing channel 0

I am trying to degug it with a 32 channel, 30000Hz file with only one minute of recording.

I am wondering if it's not because of my geometry file? Any specifics we need to pay attention to?
I am using a buzsaki 32 probe right now (4 shanks with octrodes on them).
I made the following geometry file (these are actual microns values):

37 120
33 80
29 40
20.5 0
12 20
8 60
4 100
0 140
237 120
233 80
229 40
220.5 0
212 20
208 60
204 100
200 140
437 120
433 80
429 40
420.5 0
412 20
408 60
404 100
400 140
637 120
633 80
629 40
620.5 0
612 20
608 60
604 100
600 140

in the yaml file I set  
spatial_radius: 10
(I don't know how much it should be, so I guessed 20microns cirles should be good)

Any advice?

**Comment by catubc** [comment]
Ok, So we haven't tested yass specifically on multi shank data, nor non-symmetric layouts.  But in principle it should work, and if you wish to try debugging further we can try to help.

The spatial radius deals with the distance to the nearest channel neighbour, usually in the same units as the geometry file.  So for tapered-V shanks on Buzsaki probes, you need to figure out what the distances are, usually at least 20-30 microns.  Check that.

Second, you may also wish to separate the data into 4 shanks and process them individually.  That could make debugging a bit easier.

Third, and perhaps most complex, is that the default detect neural network was trained on symmetric layouts and the V-shape may not be ideal.  But it should still work in principle, we'd need to see how many events it finds post event detection. 

Another suggestion is to perhaps try to get yass to work on more symmetric layout datasets before moving on the Buzsaki probes.  That might give you some insight into the problems.
