### ISSUE TITLE
Failed to buid, seg fault

### ISSUE THREAD

**Issue by jamesjun** [paninski-lab/yass#291]
I got a following error during the build process. Second build exited without an error but I get a seg fault when I follow the tutorial on the main page.

> (yass) jjun@ccmlin000:10chan$ yass sort config.yaml
Segmentation fault (core dumped)

> Building wheels for collected packages: yass-algorithm, multiprocess, cerberus, dill
  Building wheel for yass-algorithm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/home/jjun/conda/envs/yass/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-f51b2sb3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-f51b2sb3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v5bvxuyn --python-tag cp36
       cwd: /tmp/pip-req-build-f51b2sb3/
  Complete output (189 lines):
  /mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '0.10dev' to '0.10.dev0'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/diptest
  copying src/diptest/__init__.py -> build/lib.linux-x86_64-3.6/diptest
  copying src/diptest/_interface.py -> build/lib.linux-x86_64-3.6/diptest
  creating build/lib.linux-x86_64-3.6/yass
  copying src/yass/pipeline.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/mfm.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/pipeline_blocks.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/template.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/empty.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/util.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/command_line.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/__init__.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/geometry.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/pipeline_nn_training.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/soft_assignment.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/pipeline_original.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/pipeline_residual.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/reader.py -> build/lib.linux-x86_64-3.6/yass
  copying src/yass/array.py -> build/lib.linux-x86_64-3.6/yass
  creating build/lib.linux-x86_64-3.6/yass/deconvolve
  copying src/yass/deconvolve/match_pursuit.py -> build/lib.linux-x86_64-3.6/yass/deconvolve
  copying src/yass/deconvolve/util.py -> build/lib.linux-x86_64-3.6/yass/deconvolve
  copying src/yass/deconvolve/run.py -> build/lib.linux-x86_64-3.6/yass/deconvolve
  copying src/yass/deconvolve/deconvolve_old.py -> build/lib.linux-x86_64-3.6/yass/deconvolve
  copying src/yass/deconvolve/__init__.py -> build/lib.linux-x86_64-3.6/yass/deconvolve
  copying src/yass/deconvolve/deconv_exp_utils.py -> build/lib.linux-x86_64-3.6/yass/deconvolve
  copying src/yass/deconvolve/match_pursuit_gpu.py -> build/lib.linux-x86_64-3.6/yass/deconvolve
  copying src/yass/deconvolve/run_original.py -> build/lib.linux-x86_64-3.6/yass/deconvolve
  creating build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/mad.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/low_fr.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/util.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/run.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/duplicate.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/__init__.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/collision.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/small_ptp.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/high_fr.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/off_centered.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  copying src/yass/postprocess/duplicate_l2.py -> build/lib.linux-x86_64-3.6/yass/postprocess
  creating build/lib.linux-x86_64-3.6/yass/rf
  copying src/yass/rf/sta_fit.py -> build/lib.linux-x86_64-3.6/yass/rf
  copying src/yass/rf/util.py -> build/lib.linux-x86_64-3.6/yass/rf
  copying src/yass/rf/run.py -> build/lib.linux-x86_64-3.6/yass/rf
  copying src/yass/rf/__init__.py -> build/lib.linux-x86_64-3.6/yass/rf
  creating build/lib.linux-x86_64-3.6/yass/residual
  copying src/yass/residual/run.py -> build/lib.linux-x86_64-3.6/yass/residual
  copying src/yass/residual/__init__.py -> build/lib.linux-x86_64-3.6/yass/residual
  copying src/yass/residual/residual_gpu.py -> build/lib.linux-x86_64-3.6/yass/residual
  copying src/yass/residual/residual.py -> build/lib.linux-x86_64-3.6/yass/residual
  creating build/lib.linux-x86_64-3.6/yass/detect
  copying src/yass/detect/deduplication_old.py -> build/lib.linux-x86_64-3.6/yass/detect
  copying src/yass/detect/run.py -> build/lib.linux-x86_64-3.6/yass/detect
  copying src/yass/detect/__init__.py -> build/lib.linux-x86_64-3.6/yass/detect
  copying src/yass/detect/output.py -> build/lib.linux-x86_64-3.6/yass/detect
  copying src/yass/detect/deduplication.py -> build/lib.linux-x86_64-3.6/yass/detect
  creating build/lib.linux-x86_64-3.6/yass/preprocess
  copying src/yass/preprocess/util.py -> build/lib.linux-x86_64-3.6/yass/preprocess
  copying src/yass/preprocess/run.py -> build/lib.linux-x86_64-3.6/yass/preprocess
  copying src/yass/preprocess/__init__.py -> build/lib.linux-x86_64-3.6/yass/preprocess
  creating build/lib.linux-x86_64-3.6/yass/augment
  copying src/yass/augment/util.py -> build/lib.linux-x86_64-3.6/yass/augment
  copying src/yass/augment/run.py -> build/lib.linux-x86_64-3.6/yass/augment
  copying src/yass/augment/noise.py -> build/lib.linux-x86_64-3.6/yass/augment
  copying src/yass/augment/__init__.py -> build/lib.linux-x86_64-3.6/yass/augment
  creating build/lib.linux-x86_64-3.6/yass/config
  copying src/yass/config/__init__.py -> build/lib.linux-x86_64-3.6/yass/config
  copying src/yass/config/config.py -> build/lib.linux-x86_64-3.6/yass/config
  copying src/yass/config/validate.py -> build/lib.linux-x86_64-3.6/yass/config
  creating build/lib.linux-x86_64-3.6/yass/batch
  copying src/yass/batch/pipeline.py -> build/lib.linux-x86_64-3.6/yass/batch
  copying src/yass/batch/buffer.py -> build/lib.linux-x86_64-3.6/yass/batch
  copying src/yass/batch/generator.py -> build/lib.linux-x86_64-3.6/yass/batch
  copying src/yass/batch/util.py -> build/lib.linux-x86_64-3.6/yass/batch
  copying src/yass/batch/vectorize.py -> build/lib.linux-x86_64-3.6/yass/batch
  copying src/yass/batch/__init__.py -> build/lib.linux-x86_64-3.6/yass/batch
  copying src/yass/batch/batch.py -> build/lib.linux-x86_64-3.6/yass/batch
  copying src/yass/batch/reader.py -> build/lib.linux-x86_64-3.6/yass/batch
  creating build/lib.linux-x86_64-3.6/yass/neuralnetwork
  copying src/yass/neuralnetwork/model_denoiser.py -> build/lib.linux-x86_64-3.6/yass/neuralnetwork
  copying src/yass/neuralnetwork/__init__.py -> build/lib.linux-x86_64-3.6/yass/neuralnetwork
  copying src/yass/neuralnetwork/model_detector.py -> build/lib.linux-x86_64-3.6/yass/neuralnetwork
  creating build/lib.linux-x86_64-3.6/yass/merge
  copying src/yass/merge/util.py -> build/lib.linux-x86_64-3.6/yass/merge
  copying src/yass/merge/run.py -> build/lib.linux-x86_64-3.6/yass/merge
  copying src/yass/merge/__init__.py -> build/lib.linux-x86_64-3.6/yass/merge
  copying src/yass/merge/notch.py -> build/lib.linux-x86_64-3.6/yass/merge
  copying src/yass/merge/merge.py -> build/lib.linux-x86_64-3.6/yass/merge
  copying src/yass/merge/correlograms_phy.py -> build/lib.linux-x86_64-3.6/yass/merge
  creating build/lib.linux-x86_64-3.6/yass/explore
  copying src/yass/explore/table.py -> build/lib.linux-x86_64-3.6/yass/explore
  copying src/yass/explore/explorers.py -> build/lib.linux-x86_64-3.6/yass/explore
  copying src/yass/explore/__init__.py -> build/lib.linux-x86_64-3.6/yass/explore
  copying src/yass/explore/receptive_fields.py -> build/lib.linux-x86_64-3.6/yass/explore
  creating build/lib.linux-x86_64-3.6/yass/evaluate
  copying src/yass/evaluate/stability.py -> build/lib.linux-x86_64-3.6/yass/evaluate
  copying src/yass/evaluate/util.py -> build/lib.linux-x86_64-3.6/yass/evaluate
  copying src/yass/evaluate/__init__.py -> build/lib.linux-x86_64-3.6/yass/evaluate
  copying src/yass/evaluate/analyzer.py -> build/lib.linux-x86_64-3.6/yass/evaluate
  copying src/yass/evaluate/visualization.py -> build/lib.linux-x86_64-3.6/yass/evaluate
  copying src/yass/evaluate/stability_filters.py -> build/lib.linux-x86_64-3.6/yass/evaluate
  creating build/lib.linux-x86_64-3.6/yass/cluster
  copying src/yass/cluster/ptp_split.py -> build/lib.linux-x86_64-3.6/yass/cluster
  copying src/yass/cluster/util.py -> build/lib.linux-x86_64-3.6/yass/cluster
  copying src/yass/cluster/run.py -> build/lib.linux-x86_64-3.6/yass/cluster
  copying src/yass/cluster/__init__.py -> build/lib.linux-x86_64-3.6/yass/cluster
  copying src/yass/cluster/cluster.py -> build/lib.linux-x86_64-3.6/yass/cluster
  copying src/yass/cluster/cluster_test.py -> build/lib.linux-x86_64-3.6/yass/cluster
  copying src/yass/cluster/getptp.py -> build/lib.linux-x86_64-3.6/yass/cluster
  copying src/yass/cluster/sharpen.py -> build/lib.linux-x86_64-3.6/yass/cluster
  creating build/lib.linux-x86_64-3.6/yass/visual
  copying src/yass/visual/util.py -> build/lib.linux-x86_64-3.6/yass/visual
  copying src/yass/visual/run.py -> build/lib.linux-x86_64-3.6/yass/visual
  copying src/yass/visual/__init__.py -> build/lib.linux-x86_64-3.6/yass/visual
  copying src/yass/visual/soft_assignment.py -> build/lib.linux-x86_64-3.6/yass/visual
  copying src/yass/visual/barplots.py -> build/lib.linux-x86_64-3.6/yass/visual
  creating build/lib.linux-x86_64-3.6/yass/noise
  copying src/yass/noise/run.py -> build/lib.linux-x86_64-3.6/yass/noise
  copying src/yass/noise/__init__.py -> build/lib.linux-x86_64-3.6/yass/noise
  copying src/yass/noise/soft_assignment.py -> build/lib.linux-x86_64-3.6/yass/noise
  creating build/lib.linux-x86_64-3.6/yass/threshold
  copying src/yass/threshold/dimensionality_reduction.py -> build/lib.linux-x86_64-3.6/yass/threshold
  copying src/yass/threshold/__init__.py -> build/lib.linux-x86_64-3.6/yass/threshold
  copying src/yass/threshold/detect.py -> build/lib.linux-x86_64-3.6/yass/threshold
  creating build/lib.linux-x86_64-3.6/yass/export
  copying src/yass/export/__init__.py -> build/lib.linux-x86_64-3.6/yass/export
  copying src/yass/export/generate.py -> build/lib.linux-x86_64-3.6/yass/export
  running egg_info
  creating src/yass_algorithm.egg-info
  writing src/yass_algorithm.egg-info/PKG-INFO
  writing dependency_links to src/yass_algorithm.egg-info/dependency_links.txt
  writing entry points to src/yass_algorithm.egg-info/entry_points.txt
  writing requirements to src/yass_algorithm.egg-info/requires.txt
  writing top-level names to src/yass_algorithm.egg-info/top_level.txt
  writing manifest file 'src/yass_algorithm.egg-info/SOURCES.txt'
  reading manifest file 'src/yass_algorithm.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'src/yass_algorithm.egg-info/SOURCES.txt'
  copying src/diptest/_dip.c -> build/lib.linux-x86_64-3.6/diptest
  copying src/diptest/_diptest.c -> build/lib.linux-x86_64-3.6/diptest
  copying src/diptest/dip_crit.txt -> build/lib.linux-x86_64-3.6/diptest
  creating build/lib.linux-x86_64-3.6/yass/assets
  creating build/lib.linux-x86_64-3.6/yass/assets/config
  copying src/yass/assets/config/schema.yaml -> build/lib.linux-x86_64-3.6/yass/assets/config
  creating build/lib.linux-x86_64-3.6/yass/assets/logger
  copying src/yass/assets/logger/config.yaml -> build/lib.linux-x86_64-3.6/yass/assets/logger
  creating build/lib.linux-x86_64-3.6/yass/assets/nn_models
  copying src/yass/assets/nn_models/denoise.pt -> build/lib.linux-x86_64-3.6/yass/assets/nn_models
  copying src/yass/assets/nn_models/denoise_31.pt -> build/lib.linux-x86_64-3.6/yass/assets/nn_models
  copying src/yass/assets/nn_models/detect.pt -> build/lib.linux-x86_64-3.6/yass/assets/nn_models
  copying src/yass/assets/nn_models/detect_31.pt -> build/lib.linux-x86_64-3.6/yass/assets/nn_models
  copying src/yass/assets/nn_models/detect_single.pt -> build/lib.linux-x86_64-3.6/yass/assets/nn_models
  creating build/lib.linux-x86_64-3.6/yass/assets/phy
  copying src/yass/assets/phy/params.py -> build/lib.linux-x86_64-3.6/yass/assets/phy
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-f51b2sb3/setup.py", line 129, in <module>
      ext_modules=ext_modules,
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-f51b2sb3/setup.py", line 86, in run
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for yass-algorithm
  Running setup.py clean for yass-algorithm
  Building wheel for multiprocess (setup.py) ... done
  Created wheel for multiprocess: filename=multiprocess-0.70.9-cp36-none-any.whl size=100647 sha256=17eebffbe7aa319ef31a7e576ed79ff5139acd4228df9d4ae00a48d177d84e10
  Stored in directory: /mnt/home/jjun/.cache/pip/wheels/96/20/ac/9f1d164f7d81787cd6f4401b1d05212807d021fbbbcc301b82
  Building wheel for cerberus (setup.py) ... done
  Created wheel for cerberus: filename=Cerberus-1.3.1-cp36-none-any.whl size=54130 sha256=992605d8027e26e8edff0ef684714d23c5fb0ce99bd8af2403eba5fd84179d98
  Stored in directory: /mnt/home/jjun/.cache/pip/wheels/4f/b4/2b/83fc9a02bdbb49350a9eeb6d34753e4d7df7f77cb027e1d4b3
  Building wheel for dill (setup.py) ... done
  Created wheel for dill: filename=dill-0.3.1.1-cp36-none-any.whl size=78532 sha256=e9f1c2d4b6f58a372452eef0510115177f86a77a82885f972e761a6799655d25
  Stored in directory: /mnt/home/jjun/.cache/pip/wheels/59/b1/91/f02e76c732915c4015ab4010f3015469866c1eb9b14058d8e7
Successfully built multiprocess cerberus dill
Failed to build yass-algorithm
ERROR: tables 3.4.4 requires numexpr>=2.5.2, which is not installed.
ERROR: mountainlab-pytools 0.4.3 requires ipython, which is not installed.
ERROR: mountainlab-pytools 0.4.3 requires ipywidgets, which is not installed.
ERROR: mountainlab-pytools 0.4.3 requires numpydoc, which is not installed.
ERROR: mountainlab-pytools 0.4.3 requires requests, which is not installed.
ERROR: ml-ephys 0.2.1 requires numpydoc, which is not installed.
Installing collected packages: numpy, scipy, joblib, scikit-learn, pyyaml, six, python-dateutil, click, tqdm, dill, multiprocess, humanfriendly, coloredlogs, cerberus, parmap, patsy, pytz, pandas, statsmodels, cycler, pyparsing, kiwisolver, matplotlib, decorator, networkx, Cython, python-utils, progressbar2, h5py, yass-algorithm
  Running setup.py install for yass-algorithm ... done
Successfully installed Cython-0.29.13 cerberus-1.3.1 click-7.0 coloredlogs-10.0 cycler-0.10.0 decorator-4.4.0 dill-0.3.1.1 h5py-2.10.0 humanfriendly-4.18 joblib-0.14.0 kiwisolver-1.1.0 matplotlib-3.1.1 multiprocess-0.70.9 networkx-2.3 numpy-1.17.2 pandas-0.25.1 parmap-1.5.2 patsy-0.5.1 progressbar2-3.47.0 pyparsing-2.4.2 python-dateutil-2.8.0 python-utils-2.3.0 pytz-2019.3 pyyaml-5.1.2 scikit-learn-0.21.3 scipy-1.3.1 six-1.12.0 statsmodels-0.10.1 tqdm-4.36.1 yass-algorithm-0.10.dev0

**Comment by catubc** [comment]
Hi James. Thanks for the note.
Not completely clear what the issue is. Is the printout from one of the steps in the install script?  Are you running directly in conda environment or another environment. 

It says can't even install numpy, so not sure why that happens.  If you're still having issue, we can skype and go over the install together.
Thanks again,
