### ISSUE TITLE
ImportError: cannot import name 'run' (from yass.deconvolve.run)

### ISSUE THREAD

**Issue by jamesjun** [paninski-lab/yass#293]
(yass) jjun@ccmlin000:10chan$ yass sort config.yaml
Traceback (most recent call last):
File "/mnt/home/jjun/conda/envs/yass/bin/yass", line 6, in
from yass.command_line import cli
File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 19, in
from yass import pipeline
File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 32, in
from yass import (preprocess, detect, cluster, postprocess,
File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/deconvolve/init.py", line 1, in
from yass.deconvolve.run import run
ImportError: cannot import name 'run'

**Comment by catubc** [comment]
Hi James. So this means that yass is not installed correctly.  It's not an actual yass issue.
Let me know if you want some help with the installation.

**Comment by jamesjun** [comment]
Thanks Cat, It must have to do with the src\gpu_deconv module. I ran ‘python install setup.py —force’ in this directory and there was no error. I installed pytorch through conda. Should I have specified the exact version of pytorch? (1.1.0 according to the readme) 

-James

**Comment by catubc** [comment]
So yes, that's not sufficient, you may need to delete the previous builds.

If that doesn't work, the best way to debug is to start from beginning in a fresh clone/environment.  It should only take about 3-4minutes for everything to be installed. 

Let us know.

**Comment by jamesjun** [comment]
okay. I think installation will be much easier if you could provide
environment.yaml with all the right versions.

To generate this file, you need to run the line below in your conda
environment
`$conda env export > environment.yaml`

And I can simply run the line below to install:
`$ conda env create -f environment.yaml`

-James

**Comment by catubc** [comment]
Thanks James, we'll look into it.
