### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by llobetv** [paninski-lab/yass#296]
match_pursuit_gpu.py", line 284, in templates_to_bsplines
    coefficients = np.load(fname)

should be:
    coefficients = np.load(fname, allow_pickle=True)

-----
same in yass/deconvolve/run.py l.1005

**Comment by catubc** [comment]
Hi Victor.
Yes, you are correct, these are updated numpy flags that we missed.  
We now fixed them and pushed code back in.
Thanks.
