### ISSUE TITLE
manual merging/splitting/quality scoring?

### ISSUE THREAD

**Issue by weallen** [paninski-lab/yass#30]
Hi,

Is there any way currently to manually merge/split clusters or call clusters as good/MUA/noise? Phy's template-gui is a nice interface for this; maybe there could be a mode that allows the output to be viewed with phy?

Thanks,
Will

**Comment by edublancas** [comment]
Hi, we currently do not have a way to manually merge clusters. We are currently working on integrating YASS with phy, there is no release date but we expect it to be soon.

**Comment by pplenck** [comment]
Did you give up on it?
