### ISSUE TITLE
KeyError: 'height_list is not a file in the archive'

### ISSUE THREAD

**Issue by llobetv** [paninski-lab/yass#302]
Hi,

You probably notice it but in case not, i get this when I launch yass on 10sample/ with default config.yaml

yass.pipeline@run 28/10/2019 10:32:01 INFO YASS version: 0.10dev
yass.preprocess.run@run 28/10/2019 10:32:01 INFO # of chunks: 6
yass.preprocess.run@run 28/10/2019 10:32:01 INFO Creating temporary folder: tmp/preprocess
yass.preprocess.run@run 28/10/2019 10:32:01 INFO Output dtype for transformed data will be float32
100%|█████████████████████████████████| 6/6 [00:02<00:00,  2.95it/s]
yass.preprocess.util@merge_filtered_files 28/10/2019 10:32:04 INFO ...saving standardized file: tmp/preprocess/standardized.bin
yass.preprocess.run@run 28/10/2019 10:32:04 INFO Saving params...
yass.pipeline@initial_block 28/10/2019 10:32:04 INFO INITIAL DETECTION
   batch length to (sec):  400  (longer increase speed a bit)
   length of each seg (sec):  0.5
batch : 0,  # spikes: 6890
yass.detect.output@gather_result 28/10/2019 10:32:10 INFO gather detected spikes
yass.detect.output@gather_result 28/10/2019 10:32:11 INFO Total 839092 spikes detected
yass.detect.output@gather_result 28/10/2019 10:32:11 INFO Total 122632 spikes survived after deduplication
yass.pipeline@initial_block 28/10/2019 10:32:11 INFO INITIAL CLUSTERING
yass.cluster.run@run 28/10/2019 10:32:13 INFO Split on PTP
yass.cluster.ptp_split@run_split_on_ptp 28/10/2019 10:32:13 INFO Get Spike PTP
100%|███████████████████████████████| 12/12 [00:01<00:00,  6.60it/s]
yass.cluster.ptp_split@run_split_on_ptp 28/10/2019 10:32:15 INFO Run Split
yass.cluster.run@run 28/10/2019 10:32:19 INFO load waveforms on local channels
yass.cluster.run@run 28/10/2019 10:32:23 INFO NN denoise
yass.cluster.run@run 28/10/2019 10:32:29 INFO align waveforms on local channels
yass.cluster.run@run 28/10/2019 10:32:34 INFO starting clustering
100%|███████████████████████████████| 16/16 [00:13<00:00,  1.18it/s]
yass.cluster.util@gather_clustering_result 28/10/2019 10:32:51 INFO gathering clustering results
yass.cluster.util@gather_clustering_result 28/10/2019 10:32:51 INFO units loaded: 121
yass.cluster.util@gather_clustering_result 28/10/2019 10:32:51 INFO reindexing spikes
yass.cluster.run@run 28/10/2019 10:32:51 INFO re-estimate templates of low firing rate units
yass.postprocess.run@run 28/10/2019 10:32:51 INFO 121 units are in
yass.postprocess.run@post_process 28/10/2019 10:32:51 INFO 121 units after removing off centered units
100%|████████████████████████████| 121/121 [00:01<00:00, 107.57it/s]
yass.postprocess.run@post_process 28/10/2019 10:32:56 INFO 109 units after removing high mad units
yass.postprocess.run@post_process 28/10/2019 10:33:01 INFO 54 units after removing duplicate units
 inpput to block2:  tmp/block_1/cluster_post_process/templates.npy
yass.pipeline@iterative_block 28/10/2019 10:33:01 INFO DECONV
Processing templates:  tmp/block_1/cluster_post_process/templates.npy
 ICD TUREND ON .....
   templates NOT being updated ...
    d_gpu.neuron_discover_time:  360
   making SVD data... (todo: move to GPU)
  making temp_temp filters (todo: move to GPU)
  making template bsplines
  ... moving coefficients to cuda objects
Forward deconv only  5  sec,  0 / 12
Forward deconv only  10  sec,  1 / 12
Forward deconv only  15  sec,  2 / 12
Forward deconv only  20  sec,  3 / 12
Forward deconv only  25  sec,  4 / 12
Forward deconv only  30  sec,  5 / 12
Forward deconv only  35  sec,  6 / 12
Forward deconv only  40  sec,  7 / 12
Forward deconv only  45  sec,  8 / 12
Forward deconv only  50  sec,  9 / 12
Forward deconv only  55  sec,  10 / 12
Forward deconv only  60  sec,  11 / 12
-------------------------------------------
Total Deconv Speed  4.12  x Realtime
  gathering spike trains and shifts from deconv (todo: parallelize)
100%|██████████████████████████████| 12/12 [00:00<00:00, 108.76it/s]
   vstacking spikes (TODO initalize large array and then try to fill it...): 
   ordering spikes: 
  skipping spike deduplication step 
  saving spike_train:  (64218, 2)
yass.pipeline@iterative_block 28/10/2019 10:33:15 INFO RESIDUAL COMPUTATION
# of chunks:  12
  loading templates... tmp/block_2/deconv/templates.npy
  ... moving coefficients to cuda objects
100%|███████████████████████████████| 12/12 [00:00<00:00, 82.29it/s]
Total residual time:  0.14684128761291504
yass.pipeline@iterative_block 28/10/2019 10:33:20 INFO RECLUSTERING
yass.cluster.run@run 28/10/2019 10:33:20 INFO Split on PTP
yass.cluster.ptp_split@run_split_on_ptp 28/10/2019 10:33:20 INFO Get Spike PTP
100%|██████████████████████████████| 12/12 [00:00<00:00, 147.62it/s]
yass.cluster.ptp_split@run_split_on_ptp 28/10/2019 10:33:20 INFO Run Split
yass.cluster.run@run 28/10/2019 10:33:25 INFO load waveforms on local channels
yass.cluster.run@run 28/10/2019 10:33:29 INFO NN denoise
yass.cluster.run@run 28/10/2019 10:33:35 INFO align waveforms on local channels
yass.cluster.run@run 28/10/2019 10:33:40 INFO starting clustering
100%|███████████████████████████████| 59/59 [00:06<00:00,  8.52it/s]
yass.cluster.util@gather_clustering_result 28/10/2019 10:33:50 INFO gathering clustering results
yass.cluster.util@gather_clustering_result 28/10/2019 10:33:50 INFO units loaded: 118
yass.cluster.util@gather_clustering_result 28/10/2019 10:33:50 INFO reindexing spikes
yass.cluster.run@run 28/10/2019 10:33:50 INFO re-estimate templates of low firing rate units
yass.postprocess.run@run 28/10/2019 10:33:50 INFO 118 units are in
yass.postprocess.run@post_process 28/10/2019 10:33:50 INFO 118 units after removing off centered units
100%|████████████████████████████| 118/118 [00:01<00:00, 112.09it/s]
yass.postprocess.run@post_process 28/10/2019 10:33:55 INFO 112 units after removing high mad units
yass.postprocess.run@post_process 28/10/2019 10:34:00 INFO 57 units after removing duplicate units
yass.pipeline@pre_final_deconv 28/10/2019 10:34:00 INFO DECONV
Processing templates:  tmp/block_2/cluster_post_process/templates.npy
 ICD TUREND ON .....
   templates NOT being updated ...
    d_gpu.neuron_discover_time:  360
   making SVD data... (todo: move to GPU)
  making temp_temp filters (todo: move to GPU)
  making template bsplines
  ... moving coefficients to cuda objects
Forward deconv only  5  sec,  0 / 12
Forward deconv only  10  sec,  1 / 12
Forward deconv only  15  sec,  2 / 12
Forward deconv only  20  sec,  3 / 12
Forward deconv only  25  sec,  4 / 12
Forward deconv only  30  sec,  5 / 12
Forward deconv only  35  sec,  6 / 12
Forward deconv only  40  sec,  7 / 12
Forward deconv only  45  sec,  8 / 12
Forward deconv only  50  sec,  9 / 12
Forward deconv only  55  sec,  10 / 12
Forward deconv only  60  sec,  11 / 12
-------------------------------------------
Total Deconv Speed  4.18  x Realtime
  gathering spike trains and shifts from deconv (todo: parallelize)
100%|██████████████████████████████| 12/12 [00:00<00:00, 107.74it/s]
   vstacking spikes (TODO initalize large array and then try to fill it...): 
   ordering spikes: 
  skipping spike deduplication step 
  saving spike_train:  (63179, 2)
yass.pipeline@pre_final_deconv 28/10/2019 10:34:14 INFO RESIDUAL COMPUTATION
# of chunks:  12
  loading templates... tmp/pre_final_deconv/deconv/templates.npy
  ... moving coefficients to cuda objects
100%|███████████████████████████████| 12/12 [00:00<00:00, 89.27it/s]
Total residual time:  0.13526654243469238
yass.pipeline@pre_final_deconv 28/10/2019 10:34:19 INFO SOFT NOISE ASSIGNMENT
100%|███████████████████████████████| 12/12 [00:00<00:00, 67.60it/s]
yass.pipeline@pre_final_deconv 28/10/2019 10:34:19 INFO POST DECONV MERGE
yass.merge.run@run 28/10/2019 10:34:19 INFO finding merge candidates
yass.merge.merge@__init__ 28/10/2019 10:34:19 INFO 57 units in
yass.merge.merge@__init__ 28/10/2019 10:34:19 INFO finding candidates using ptp
yass.merge.run@run 28/10/2019 10:34:19 INFO merging pairs
100%|███████████████████████████████| 40/40 [00:05<00:00,  7.86it/s]
yass.merge.run@run 28/10/2019 10:34:27 INFO udpating templates and spike train
yass.merge.run@run 28/10/2019 10:34:27 INFO Number of units after merge: 42
yass.pipeline@pre_final_deconv 28/10/2019 10:34:27 INFO Remove Low Firing Rate Units
yass.postprocess.run@run 28/10/2019 10:34:27 INFO 42 units are in
yass.postprocess.run@post_process 28/10/2019 10:34:27 INFO 42 units after removing low fr units
yass.pipeline@final_deconv 28/10/2019 10:34:27 INFO FINAL DECONV
Processing templates:  tmp/pre_final_deconv/post_deconv_post_process/templates.npy
 ICD TUREND ON .....
   templates being updated every  60  sec
    d_gpu.neuron_discover_time:  360

   making SVD data... (todo: move to GPU)
  making temp_temp filters (todo: move to GPU)
  making template bsplines
  ... moving coefficients to cuda objects
 Forward pass time  5
 Forward pass time  10
 Forward pass time  15
 Forward pass time  20
 Forward pass time  25
 Forward pass time  30
 Forward pass time  35
 Forward pass time  40
 Forward pass time  45
 Forward pass time  50
 Forward pass time  55
 Forward pass time  60
    UPDATING TEMPLATES   <<<<<<<<<<<<<
   making SVD data... (todo: move to GPU)
  making temp_temp filters (todo: move to GPU)
  making template bsplines
  ... moving coefficients to cuda objects
time index:  60
 chunk_id:  0
 d_gpu.reader.n_batche:  12
 time_index:  60

   making SVD data... (todo: move to GPU)
   loading SVD from disk...
  making temp_temp filters (todo: move to GPU)
.... loading temp-temp from disk
  making template bsplines
  ... loading coefficients from disk
  ... moving coefficients to cuda objects
 Backward pass time  5
 Backward pass time  10
 Backward pass time  15
 Backward pass time  20
 Backward pass time  25
 Backward pass time  30
 Backward pass time  35
 Backward pass time  40
 Backward pass time  45
 Backward pass time  50
 Backward pass time  55
 Backward pass time  60
  DONE BACKWARD PASS: 
 chunk_id:  12
 d_gpu.reader.n_batche:  12
 time_index:  60
-------------------------------------------
Total Deconv Speed  2.45  x Realtime
  gathering spike trains and shifts from deconv (todo: parallelize)
  0%|                                        | 0/12 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/bin/yass", line 10, in <module>
    sys.exit(cli())
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 71, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 172, in run
    run_chunk_sec = CONFIG.final_deconv_chunk)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 473, in final_deconv
    run_chunk_sec=run_chunk_sec)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 141, in run
    run_chunk_sec)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 307, in deconv_ONgpu2
    scale_list = data['height_list']
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/numpy/lib/npyio.py", line 266, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'height_list is not a file in the archive'

**Comment by catubc** [comment]
Thanks.  This is not a bug, just we haven't finished coding that function in the very last step of processing which provides a soft-assignment of spikes.  For now you can get the final spike trains and templates here:

/tmp/final_deconv/deconv/spike_train.npy
/tmp/final_deconv/deconv/templates.npy

**Comment by jamesjun** [comment]
The same issue persists and I can't find the files at that location.

**Comment by jamesjun** [comment]
I found 
`pre_final_deconv/deconv/templates.npy` and `pre_final_deconv/deconv/spike_train.npy`.
Can I use those?

**Comment by catubc** [comment]
Hi James.  The spike train and templates at those locations are suboptimal.  The final_deconv directory should contain the best output.  And the reported bug above should only occur on final_deconv output.

Can you please post the error log you get? Thanks.

**Comment by jamesjun** [comment]
(yass) jjun@ccmlin000:10chan$ yass sort config.yaml
yass.pipeline@run 20/11/2019 20:02:34 INFO YASS version: 0.10dev
yass.preprocess.run@run 20/11/2019 20:02:34 INFO # of chunks: 6
yass.preprocess.run@run 20/11/2019 20:02:34 INFO Temporary folder tmp/preprocess already exists, output will be stored there
yass.preprocess.run@run 20/11/2019 20:02:34 INFO Output dtype for transformed data will be float32
yass.pipeline@initial_block 20/11/2019 20:02:34 INFO INITIAL DETECTION
yass.pipeline@initial_block 20/11/2019 20:02:34 INFO INITIAL CLUSTERING
 inpput to block2:  tmp/block_1/cluster_post_process/templates.npy
yass.pipeline@iterative_block 20/11/2019 20:02:34 INFO DECONV
Processing templates:  tmp/block_1/cluster_post_process/templates.npy
yass.pipeline@iterative_block 20/11/2019 20:02:34 INFO RESIDUAL COMPUTATION
yass.pipeline@iterative_block 20/11/2019 20:02:34 INFO RECLUSTERING
yass.pipeline@pre_final_deconv 20/11/2019 20:02:34 INFO DECONV
Processing templates:  tmp/block_2/cluster_post_process/templates.npy
yass.pipeline@pre_final_deconv 20/11/2019 20:02:34 INFO RESIDUAL COMPUTATION
yass.pipeline@pre_final_deconv 20/11/2019 20:02:34 INFO SOFT NOISE ASSIGNMENT
yass.pipeline@pre_final_deconv 20/11/2019 20:02:34 INFO POST DECONV MERGE
yass.pipeline@pre_final_deconv 20/11/2019 20:02:34 INFO Remove Low Firing Rate Units
yass.pipeline@final_deconv 20/11/2019 20:02:34 INFO FINAL DECONV
Processing templates:  tmp/pre_final_deconv/post_deconv_post_process/templates.npy
 ICD TUREND ON .....
   templates being updated every  60  sec
    d_gpu.neuron_discover_time:  360
-------------------------------------------
Total Deconv Speed  28571.43  x Realtime
  gathering spike trains and shifts from deconv (todo: parallelize)
  0%|                                                                                                                                                                                       | 0/12 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/home/jjun/conda/envs/yass/bin/yass", line 10, in <module>
    sys.exit(cli())
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 71, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 172, in run
    run_chunk_sec = CONFIG.final_deconv_chunk)
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 473, in final_deconv
    run_chunk_sec=run_chunk_sec)
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 141, in run
    run_chunk_sec)
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 307, in deconv_ONgpu2
    scale_list = data['height_list']
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/numpy/lib/npyio.py", line 266, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'height_list is not a file in the archive'

**Comment by catubc** [comment]
Hi James. Thanks for this, yes, it is a bug, we fixed it today and will push an update shortly.

**Comment by catubc** [comment]
This should be solved now.
