### ISSUE TITLE
yass.pipeline@pre_final_deconv : size mismatch for out.weight: copying a param with shape torch.Size([1, 56]) from checkpoint, the shape in current model is torch.Size([1, 128]).

### ISSUE THREAD

**Issue by llobetv** [paninski-lab/yass#310]
Hi guys, 
I just try the new release and I get this error for both detection with nn and final deconv (if I use threshold detection). It seems to be the same problem in the two cases. 
I can provide you my data if you want.
Best,
Victor

yass.pipeline@run 11/12/2019 12:02:48 INFO YASS version: 0.10dev
yass.preprocess.run@run 11/12/2019 12:02:48 INFO # of chunks: 581
yass.preprocess.run@run 11/12/2019 12:02:48 INFO Creating temporary folder: tmp/preprocess
yass.preprocess.run@run 11/12/2019 12:02:48 INFO Output dtype for transformed data will be float32
584it [00:21, 27.09it/s]                                                        
yass.preprocess.util@merge_filtered_files 11/12/2019 12:03:11 INFO ...saving standardized file: tmp/preprocess/standardized.bin
yass.preprocess.run@run 11/12/2019 12:03:22 INFO Saving params...
yass.pipeline@initial_block 11/12/2019 12:03:22 INFO INITIAL DETECTION
   batch length to (sec):  50  (longer increase speed a bit)
   length of each seg (sec):  0.5
100%|███████████████████████████████████████████| 59/59 [00:29<00:00,  1.97it/s]
yass.detect.output@gather_result 11/12/2019 12:03:53 INFO gather detected spikes
yass.detect.output@gather_result 11/12/2019 12:03:57 INFO Total 125731580 spikes detected
yass.detect.output@gather_result 11/12/2019 12:03:57 INFO Total 10383577 spikes survived after deduplication
yass.pipeline@initial_block 11/12/2019 12:04:16 INFO INITIAL CLUSTERING
yass.cluster.run@run 11/12/2019 12:04:16 INFO Split on PTP
yass.cluster.ptp_split@run_split_on_ptp 11/12/2019 12:04:16 INFO Get Spike PTP
100%|███████████████████████████████████████████| 12/12 [00:00<00:00, 81.94it/s]
yass.cluster.ptp_split@run_split_on_ptp 11/12/2019 12:04:18 INFO Run Split
yass.cluster.run@run 11/12/2019 12:04:41 INFO load waveforms on local channels
yass.cluster.run@run 11/12/2019 12:04:49 INFO denoise
100%|███████████████████████████████████████████| 45/45 [01:08<00:00,  1.52s/it]
yass.cluster.run@run 11/12/2019 12:05:57 INFO align waveforms on local channels
yass.cluster.run@run 11/12/2019 12:06:16 INFO starting clustering
100%|███████████████████████████████████████████| 45/45 [04:11<00:00,  5.59s/it]
yass.cluster.util@gather_clustering_result 11/12/2019 12:10:31 INFO gathering clustering results
yass.cluster.util@gather_clustering_result 11/12/2019 12:10:31 INFO units loaded: 1758
yass.cluster.util@gather_clustering_result 11/12/2019 12:10:31 INFO reindexing spikes
tmp/block_1/cluster/templates.npy
yass.postprocess.run@run 11/12/2019 12:10:32 INFO 1758 units are in
yass.postprocess.run@post_process 11/12/2019 12:10:32 INFO 990 units after removing off centered units
994it [00:04, 233.96it/s]                                                       
yass.postprocess.run@post_process 11/12/2019 12:10:40 INFO 873 units after removing high mad units
yass.postprocess.run@post_process 11/12/2019 12:10:45 INFO 188 units after removing duplicate units
 inpput to block2:  tmp/block_1/cluster_post_process/templates.npy
yass.pipeline@iterative_block 11/12/2019 12:10:45 INFO DECONV
... deconv using GPU device:  0
 ICD TUREND ON .....
   templates NOT being updated ...
    d_gpu.neuron_discover_time:  360
   making SVD data... (todo: move to GPU)
  making temp_temp filters (todo: move to GPU)
  making template bsplines
  ... moving coefficients to cuda objects
Forward deconv only  5  sec,  0 / 12
Forward deconv only  10  sec,  1 / 12
Forward deconv only  15  sec,  2 / 12
Forward deconv only  20  sec,  3 / 12
Forward deconv only  25  sec,  4 / 12
Forward deconv only  30  sec,  5 / 12
Forward deconv only  35  sec,  6 / 12
Forward deconv only  40  sec,  7 / 12
Forward deconv only  45  sec,  8 / 12
Forward deconv only  50  sec,  9 / 12
Forward deconv only  55  sec,  10 / 12
Forward deconv only  60  sec,  11 / 12
-------------------------------------------
Total Deconv Speed  3.68  x Realtime
  gathering spike trains and shifts from deconv (todo: parallelize)
100%|███████████████████████████████████████████| 12/12 [00:00<00:00, 47.50it/s]
   vstacking spikes (TODO initalize large array and then try to fill it...): 
   ordering spikes: 
  skipping spike deduplication step 
  saving spike_train:  (117888, 2)
yass.pipeline@iterative_block 11/12/2019 12:11:02 INFO RESIDUAL COMPUTATION
# of chunks:  12
100%|███████████████████████████████████████████| 12/12 [00:00<00:00, 28.45it/s]
Total residual time:  0.422757625579834
yass.pipeline@iterative_block 11/12/2019 12:11:07 INFO RECLUSTERING
yass.cluster.run@run 11/12/2019 12:11:07 INFO Split on PTP
yass.cluster.ptp_split@run_split_on_ptp 11/12/2019 12:11:07 INFO Get Spike PTP
100%|██████████████████████████████████████████| 12/12 [00:00<00:00, 118.19it/s]
yass.cluster.ptp_split@run_split_on_ptp 11/12/2019 12:11:07 INFO Run Split
yass.cluster.run@run 11/12/2019 12:11:13 INFO load waveforms on local channels
yass.cluster.run@run 11/12/2019 12:11:18 INFO denoise
100%|█████████████████████████████████████████| 241/241 [00:09<00:00, 26.30it/s]
yass.cluster.run@run 11/12/2019 12:11:27 INFO align waveforms on local channels
yass.cluster.run@run 11/12/2019 12:11:33 INFO starting clustering
242it [00:09, 25.01it/s]                                                        
yass.cluster.util@gather_clustering_result 11/12/2019 12:11:46 INFO gathering clustering results
yass.cluster.util@gather_clustering_result 11/12/2019 12:11:46 INFO units loaded: 248
yass.cluster.util@gather_clustering_result 11/12/2019 12:11:46 INFO reindexing spikes
tmp/block_2/cluster/templates.npy
yass.postprocess.run@run 11/12/2019 12:11:46 INFO 248 units are in
yass.postprocess.run@post_process 11/12/2019 12:11:46 INFO 197 units after removing off centered units
198it [00:01, 168.65it/s]                                                       
yass.postprocess.run@post_process 11/12/2019 12:11:52 INFO 134 units after removing high mad units
yass.postprocess.run@post_process 11/12/2019 12:11:57 INFO 51 units after removing duplicate units
yass.pipeline@pre_final_deconv 11/12/2019 12:11:57 INFO DECONV
... deconv using GPU device:  0
 ICD TUREND ON .....
   templates NOT being updated ...
    d_gpu.neuron_discover_time:  360
   making SVD data... (todo: move to GPU)
  making temp_temp filters (todo: move to GPU)
  making template bsplines
  ... moving coefficients to cuda objects
Forward deconv only  5  sec,  0 / 12
Forward deconv only  10  sec,  1 / 12
Forward deconv only  15  sec,  2 / 12
Forward deconv only  20  sec,  3 / 12
Forward deconv only  25  sec,  4 / 12
Forward deconv only  30  sec,  5 / 12
Forward deconv only  35  sec,  6 / 12
Forward deconv only  40  sec,  7 / 12
Forward deconv only  45  sec,  8 / 12
Forward deconv only  50  sec,  9 / 12
Forward deconv only  55  sec,  10 / 12
Forward deconv only  60  sec,  11 / 12
-------------------------------------------
Total Deconv Speed  4.79  x Realtime
  gathering spike trains and shifts from deconv (todo: parallelize)
100%|███████████████████████████████████████████| 12/12 [00:00<00:00, 63.81it/s]
   vstacking spikes (TODO initalize large array and then try to fill it...): 
   ordering spikes: 
  skipping spike deduplication step 
  saving spike_train:  (105477, 2)
yass.pipeline@pre_final_deconv 11/12/2019 12:12:10 INFO RESIDUAL COMPUTATION
# of chunks:  12
100%|███████████████████████████████████████████| 12/12 [00:00<00:00, 28.24it/s]
Total residual time:  0.4262068271636963
yass.pipeline@pre_final_deconv 11/12/2019 12:12:15 INFO SOFT ASSIGNMENT
Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/bin/yass", line 10, in <module>
    sys.exit(cli())
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 71, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 164, in run
    run_chunk_sec = CONFIG.clustering_chunk)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 423, in pre_final_deconv
    compute_template_soft=False)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/soft_assignment/run.py", line 57, in run
    detector.load(CONFIG.neuralnetwork.detect.filename)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/neuralnetwork/model_detector.py", line 145, in load
    self.load_state_dict(checkpoint)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Detect:
	size mismatch for out.weight: copying a param with shape torch.Size([1, 56]) from checkpoint, the shape in current model is torch.Size([1, 128]).

**Comment by Dradeliomecus** [comment]
This issue is also solved by changing the spatial radius to get the same number of neighbors as in the "detect.pt" file.
See my answer in #298

**Comment by catubc** [comment]
Hi. Thank you for the reply. Yes, this issue has to do with the neural networks being trained to expect a certain number of channels as input.  In some - but not all - cases changing the spatial radius on the detection step will fix this problem (i.e. it will result in putting the correct number of channels and waveeforms into the NN-detect step).

As an alternative, the neural networks can be retrained completely from scratch on any new dataset.  This feature will be updated in the documentation soon, but for now here are the steps:

1.  Train new neural networks based on any new dataset.  The NNs being trained will take the default radius, geometry and spike waveform as input and generate new networks. Here's the command:

yass train [PATH TO CONFIG]/config.yaml

2.  This command will generate a directory called: [PATH TO DATA]/tmp/nn_train.  Find that that and these 2 files: "denoise.pt" and "detect.pt".  

3.  Insert the paths to these 2 networks in the config.yaml file under the "neuralnetwork" heading.  And then run "yass sort ..." as usual.

I hope that this is helpful, let us know if you need more help.

**Comment by catubc** [comment]
This should have been solved in latest YASS release.
