### ISSUE TITLE
Fixing yass version

### ISSUE THREAD

**Issue by edublancas** [paninski-lab/yass#316]
Answering question 1 from your email (@catubc):

Package version is determined by the `setup.py` file here:

https://github.com/paninski-lab/yass/blob/53a42543b62be8750ad5851907f4e97304d14978/setup.py#L53

As you can see, it loads a whatever value is assigned to a variable called `__version__` in the init file:

https://github.com/paninski-lab/yass/blob/53a42543b62be8750ad5851907f4e97304d14978/src/yass/__init__.py#L18

There are two approaches here:

1) Just manually modify __version__ in the init file before creating a new release
2) Use a tool to automate this process (I recommend [this one](https://github.com/warner/python-versioneer))

Let me know if you have any questions

**Comment by catubc** [comment]
Thanks.  We used option 1. for now.
