### ISSUE TITLE
Including pytorch as part of the installation process

### ISSUE THREAD

**Issue by edublancas** [paninski-lab/yass#317]
Question 2 from @catubc:

To make `pip install yass` also install pytorch, `setup.py` has to be updated:

https://github.com/paninski-lab/yass/blob/53a42543b62be8750ad5851907f4e97304d14978/setup.py#L28

Adding pytorch to that list will work, but it will be equivalent to doing `pip install pytorch`, does that work?

I'm guessing the distribution package when doing `conda install pytorch` is the same as in pip but I might be wrong, please let me know.

**Comment by catubc** [comment]
Thanks for the response.  For some reason `conda install pytorch` seems to be more reliable (I think the installed dependency list is better maintained?).  If that command could be run after `pip install .`, that's probably all we can ask for now.
