### ISSUE TITLE
error running "yass config_sample.yaml"

### ISSUE THREAD

**Issue by vncntprvst** [paninski-lab/yass#32]
Hi,
Just following the [example section](https://github.com/paninski-lab/yass#example), when I tried to run yass on the sample data, I got this error. 

`C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\command_line.py:35: De
precationWarning: class Preprocessor is deprecated: (Use function in preprocess
module, see examples/preprocess.py)
  pp = Preprocessor(cfg)
INFO:yass.preprocessing:Preprocessing the data in progress...
C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\progressbar\bar.py:223: Dep
recationWarning: The usage of `maxval` is deprecated, please use `max_value` ins
tead
  '`max_value` instead', DeprecationWarning)
2017-12-09 19:40:12.632881: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\
35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\yass\Scripts\yass-script.py", line 11, in
<module>
    load_entry_point('yass-algorithm==0.4.dev0', 'console_scripts', 'yass')()
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\command_line.p
y", line 36, in main
    score, spike_index_clear, spike_index_collision = pp.process()
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\preprocessing.
py", line 157, in process
    BUFF, Time)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\preprocessing.
py", line 250, in batch_process
    self.nnTriage
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\neuralnetwork\
detect.py", line 115, in nn_detection
    idx_clean = triage_prob[spike_index[:,0],spike_index[:,1]] > th_triage
IndexError: index 188 is out of bounds for axis 0 with size 4` 

I'm intrigued by that statment:
_Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2_
Should I build TensorFlow from source? (I installed it with Conda).

**Comment by edublancas** [comment]
Hi, thanks for reporting the issue. We are digging into it and will fix it soon.

If you want to get rid of that error you have two options, either build from source or use a pre-compiled version, I recommend you the latter. Check this out for more info https://www.tensorflow.org/install/

**Comment by vncntprvst** [comment]
OK, thanks. Will try that.

**Comment by vncntprvst** [comment]
To further clarify this issue: 
installing yass with pip (i.e. `pip install .`) does include installing tensorflow, in this case tensorflow-1.4.0-cp35-cp35m-win_amd64.whl . This is the same as following the default procedure from Tensorflow's install instructions, such as `pip install --ignore-installed --upgrade tensorflow `. The original error stays the same: `Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2 `. This issue is referenced here: [https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u](https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u)
From there, two options are available: installing from source, as indicated above, or installing the GPU version (presently, tensorflow_gpu-1.4.0-cp35-cp35m-win_amd64.whl). The latter solves the issue, under the condition that the GPU as enough memory to deal with data (at least that's my understanding).  If that's not case, one may get error such as this:
```

2017-12-11 14:38:41.998312: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu
\PY\35\tensorflow\core\common_runtime\bfc_allocator.cc:685] Stats:
Limit:                    65081344
InUse:                    51800832
MaxInUse:                 61840384
NumAllocs:                      53
MaxAllocSize:             51062784

2017-12-11 14:38:41.998312: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu
\PY\35\tensorflow\core\common_runtime\bfc_allocator.cc:277] **__________________
_***************************************************xxxxxxxxxxxxxxxxxxxxxxxxxxxx

2017-12-11 14:38:41.998312: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu
\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Resource exhausted: OOM when
 allocating tensor with shape[10,1,10120,10,8]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\c
lient\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\c
lient\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\f
ramework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocat
ing tensor with shape[10,10,1,10120,8]
         [[Node: Gather_1 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate
_indices=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat_1,
 Gather/indices/_29)]]
         [[Node: Where/_37 = _Recv[client_terminated=false, recv_device="/job:lo
calhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/ta
sk:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_139_Where", ten
sor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\yass\Scripts\yass-script.py", line 11, in
<module>
    load_entry_point('yass-algorithm==0.4.dev0', 'console_scripts', 'yass')()
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\command_line.p
y", line 36, in main
    score, spike_index_clear, spike_index_collision = pp.process()
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\preprocessing.
py", line 157, in process
    BUFF, Time)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\preprocessing.
py", line 250, in batch_process
    self.nnTriage
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\neuralnetwork\
detect.py", line 107, in nn_detection
    local_max_idx, score_train, energy_val, triage_prob  = sess.run(result, feed
_dict={x_tf: X_batch})
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\c
lient\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\c
lient\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\c
lient\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\c
lient\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocat
ing tensor with shape[10,10,1,10120,8]
         [[Node: Gather_1 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate
_indices=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat_1,
 Gather/indices/_29)]]
         [[Node: Where/_37 = _Recv[client_terminated=false, recv_device="/job:lo
calhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/ta
sk:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_139_Where", ten
sor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Gather_1', defined at:
  File "C:\ProgramData\Anaconda2\envs\yass\Scripts\yass-script.py", line 11, in
<module>
    load_entry_point('yass-algorithm==0.4.dev0', 'console_scripts', 'yass')()
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\command_line.p
y", line 36, in main
    score, spike_index_clear, spike_index_collision = pp.process()
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\preprocessing.
py", line 157, in process
    BUFF, Time)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\preprocessing.
py", line 250, in batch_process
    self.nnTriage
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\neuralnetwork\
detect.py", line 45, in nn_detection
    triage_prob_tf = nnt.triage_prob(x_tf, T_small+2*buff, nneigh, c_idx)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\neuralnetwork\
nntriage.py", line 98, in triage_prob
    temp = tf.transpose( tf.gather( zero_added_layer11, c_idx ), [0,2,3,1,4] )
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\o
ps\array_ops.py", line 2486, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\o
ps\gen_array_ops.py", line 1833, in gather
    validate_indices=validate_indices, name=name)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\f
ramework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\f
ramework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\tensorflow\python\f
ramework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-
access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor wit
h shape[10,10,1,10120,8]
         [[Node: Gather_1 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate
_indices=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat_1,
 Gather/indices/_29)]]
         [[Node: Where/_37 = _Recv[client_terminated=false, recv_device="/job:lo
calhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/ta
sk:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_139_Where", ten
sor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by vncntprvst** [comment]
The message `Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2` is actually just a warning, not an error, as explained [here](https://stackoverflow.com/questions/43134753/tensorflow-wasnt-compiled-to-use-sse-etc-instructions-but-these-are-availab).

So back to square one. Re-posting the error message below:
 ```
 File "C:\ProgramData\Anaconda2\envs\yass\Scripts\yass-script.py", line 11, in
<module>
    load_entry_point('yass-algorithm==0.4.dev0', 'console_scripts', 'yass')()
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\command_line.p
y", line 36, in main
    score, spike_index_clear, spike_index_collision = pp.process()
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\preprocessing.
py", line 157, in process
    BUFF, Time)
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\preprocessing.
py", line 250, in batch_process
    self.nnTriage
  File "C:\ProgramData\Anaconda2\envs\yass\lib\site-packages\yass\neuralnetwork\
detect.py", line 115, in nn_detection
    idx_clean = triage_prob[spike_index[:,0],spike_index[:,1]] > th_triage
IndexError: index 188 is out of bounds for axis 0 with size 4

```

**Comment by edublancas** [comment]
Thanks, the reason why YASS does not install tensorflow by default is exactly to avoid the warning (we expect users to install tensorflow by themselves so they choose whatever method they prefer), but I think we should be clear about it. Thanks for reporting this issue, in the next release we will be clear about this.

Regarding the `IndexError: index 188 is out of bounds for axis 0 with size 4` issue, we are currently working on this, will let you know when it's fixed.

This bug was probably introduced in version 0.3, so if you want to try yass you can install version 0.2 `pip install yass-algorithm==0.2`

**Comment by vncntprvst** [comment]
After installing version 0.2,  I first got this error:
`FileNotFoundError: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda2\\envs\\yass\\lib\\site-packages\\yass\\assets\\models\\detect_nn1.yaml'`
So I copied the missing file from the source directory.
Then I got this:
`Traceback (most recent call last):
  File "c:\programdata\anaconda2\envs\yass\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda2\envs\yass\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda2\envs\yass\Scripts\yass.exe\__main__.py", line 9
, in <module>
  File "c:\programdata\anaconda2\envs\yass\lib\site-packages\yass\command_line.py", line 37, in main
    score, spike_index_clear, spike_index_collision = pp.process()
  File "c:\programdata\anaconda2\envs\yass\lib\site-packages\yass\preprocessing.py", line 107, in process
    self.nnDetector = NeuralNetDetector(self.config)
  File "c:\programdata\anaconda2\envs\yass\lib\site-packages\yass\neuralnet.py",
 line 59, in __init__
    R1, R2, R3 = self.filters_dict['size']
TypeError: 'int' object is not iterable`

**Comment by edublancas** [comment]
Ok, I will dig into that. It's probably easier to fix the original error `IndexError: index 188 is out of bounds for axis 0 with size 4`. I'll let you know when it's done. Thanks again for reporting it!

**Comment by edublancas** [comment]
Ok, I fixed the problem. We recently simplified the YASS configuration file and I accidentally put "nn" as the detection method for the example. The neural network bundled with YASS only works with the data we are working with in the lab  so any other data, as the one used for the example, breaks the detector (there's a tutorial for training a neural network detector for other types of data).

So I just changed the detection method for "threshold" in the example and it works. This is the code I used to check it.


```shell
# create test env
conda create --name test -y
source activate test

# install last stable version
pip install yass-algorithm

# clone repo to get the sample data
git clone https://github.com/paninski-lab/yass

# move to the examples folder and run yass in the sample data
cd yass/examples
yass config_sample.yaml

# see the spike train
cat data/spike_train.csv

# remove test env
conda env remove --name test -y
```

Let me know if it works now so I can close this issue.

**Comment by vncntprvst** [comment]
Yep, it works. 
Thanks for the quick debugging.
