### ISSUE TITLE
Weird spike detection at deconv cutoffs

### ISSUE THREAD

**Issue by Dradeliomecus** [paninski-lab/yass#323]
Hi,

I have successfully generated phy files that I can open with my data using yass! (it takes about 40 minutes on my dataset with an RTX 2080, but it works!).

However I have found on some spikes something that I find weird (see the following images)

![weird_unit_deconv](https://user-images.githubusercontent.com/3465310/78701798-ea3fc080-7907-11ea-8da3-14055d686b73.png)
![weird_unit_deconv_2](https://user-images.githubusercontent.com/3465310/78701823-f297fb80-7907-11ea-86f5-987181dccd87.png)

The weird thing is in the spiking rate. As you can see, for some spikes (there are more than 2, but I uploaded only 2 pictures), there is a sudden shift in spiking rate at some times.
Now this shift doesn't happen for all spikes, but when it happens, it's always at a multiple of 300s (the recording is 1880s long on 64 channels).
This multiple of 300s makes me think is has to do with the "deconv" in your algorithm, since it does it on 300s at a time.

So I'm not 100% sure, but I would guess there is a problem somewhere where some spikes in some 300s windows are not found properly.

Thank you!

**Comment by jinhyunglee** [comment]
thanks for the report. I don't think this is necessarily a bug but what the algorithm is expected to do.

What type of data is it? Here, we are focusing on retina multi-electrode array data where we assume slow drift and also rank-1 variability(meaning the shape remains the same but the size changes) per channel in waveform over time.

If waveform drifts rapidly (i.e. updating every 300 seconds is not sufficient) or its shape changes over time (not just height but the actual shape), then what you are seeing can happen.

Another possibility: I see that you are using no neural net version of yass. This one will miss lots of small neurons. Then, if the size of the unit (that you are showing above) is getting smaller and smaller over time, the matching pursuit algorithm will pick up spikes of missed neurons (which are small) more and more.

The gradual increase suggests that the latter could be the case.
I suggest using nn version.

**Comment by Dradeliomecus** [comment]
My dataset if from the cerebellar cortex.

We are mainly focusing on the Purkinje cell, which have a pretty big soma and have a high firing rate (about 100 Hz).
Their shape (and the shape of interneurons and other neurons present there) should not change over time. Maybe I should adjust the 'config.yaml' file accordingly to reflect this?

What made me think it comes from deconv is that the sudden shift in firing rate (that yass extracted) is always at exactly 300 - 600 - 900 - 1200 - 1500 and 1800s (which are the exact cutoffs of deconv).

I'm planning on training the neural network (using the link catubc gave me in #321 ) in the next few days to see if anything changes.

**Comment by catubc** [comment]
Thanks for this report.  There are several things including what @jinhyunglee suggested. See below.  It's not clear how large the amplitude of these found neurons is, also what good neurons look like.  

1. Run with drift correction turned off and see if this makes much difference. If you're doing headfixed mouse then movement will still be present, but electric fish or other animals, we're not sure.

2. Train NNs as this may improve recovery of small neurons as noted above.

If you're still having issues, you can also share your /output folder with us and we can take a quick look (64 channels is still relatively small).

**Comment by Dradeliomecus** [comment]
I don't have a /output folder. Are you talking about the /tmp folder or /phy folder?

I am working on headfixed mice. I turned off the drift correction and I am no longer seeing this, thank you!

**Comment by catubc** [comment]
The output folder is /tmp/output.
