### ISSUE TITLE
"low-pass" and "high-pass" filtering definitions need to be switched

### ISSUE THREAD

**Issue by jkbhagatio** [paninski-lab/yass#328]
I've noticed in the default `config.yaml` file, under `preprocess`, `low_pass_freq` is set to 300 hz, and the `high_factor` is set to 0.1 * the sampling rate. 

Since by definition a low pass filter allows all frequencies below its cutoff, and a high pass filter allows all frequences above its cutoff, these terms are misused and should be switched. I don't know where all else in the code this change needs to be made.

**Comment by catubc** [comment]
Thank you. We will eventually make these changes, but it will take time to propagate them.
catubc
