### ISSUE TITLE
Clustering doesn't finish on some datasets

### ISSUE THREAD

**Issue by wueric** [paninski-lab/yass#330]
One of the clustering steps appears to get stuck. Doesn't crash. Happens consistently on this particular recording. Number of units reported in the first clustering step is abnormally high when compared to comparable datasets with the same config (~8000 vs ~1500)

Happy to share the offending dataset and the config.

Messages from YASS around when this happens (gets stuck at the very bottom):

yass.pipeline@iterative_block 15/07/2020 12:31:13 INFO RECLUSTERING
yass.cluster.run@run 15/07/2020 12:31:14 INFO Split on PTP
yass.cluster.ptp_split@run_split_on_ptp 15/07/2020 12:31:14 INFO Get Spike PTP
100%|██████████████████████████| 300/300 [00:10<00:00, 27.70it/s]
yass.cluster.ptp_split@run_split_on_ptp 15/07/2020 12:31:26 INFO Run Split
yass.cluster.run@run 15/07/2020 12:31:59 INFO load waveforms on local channels
yass.cluster.run@run 15/07/2020 12:32:27 INFO NN denoise
yass.cluster.run@run 15/07/2020 12:34:29 INFO align waveforms on local channels
yass.cluster.run@run 15/07/2020 12:35:20 INFO starting clustering

**Comment by catubc** [comment]
Hi Eric. Yes, please do share the dataset, the log is not clear why the hang up occurs.  I can share a dropbox link, or better yet, you can send us a shared google drive link.

**Comment by wueric** [comment]
Sent you and Peter an email
