### ISSUE TITLE
noise.py: invalid value encountered in true_divide and invalid value encountered in greater dist_in = cover_by_dist > 0.1

### ISSUE THREAD

**Issue by alinaheukamp** [paninski-lab/yass#335]
Hi,

I'm running Yass on the AWS on a MEA retina recording.

I get the following errors:

/home/ubuntu/yass/src/yass/noise.py:242: RuntimeWarning: invalid value encountered in true_divide
and
/home/ubuntu/yass/src/yass/noise.py:252: RuntimeWarning: invalid value encountered in greater dist_in = cover_by_dist > 0.1

I attached a screenshot.

I tried this for two different large recordings (each several hours, 252 electrodes) and in both cases I got this same error. When I tried it on a smaller file (the first few minutes of one of the large files) it worked without problems.

Any idea what it could be? Did you encounter this before?

Thanks
Alina
<img width="1422" alt="Screen Shot 2020-10-15 at 17 45 08" src="https://user-images.githubusercontent.com/58134512/96149571-2769b880-0f12-11eb-8eaf-360bb1dd1c8c.png">

**Comment by catubc** [comment]
Hi Alina
Sorry for the delay
Is this an issue for you still?

The soft_assignment step is still having some bugs/issues and we are working on fixing them.  An alternative is to bypass this step which is not used by everyone.

Thanks

**Comment by alinaheukamp** [comment]
Hi,

Yes, this is still an issue for us. I'm waiting for the fix to try it again, so please let me know when you have it fixed.

Thanks!

**Comment by catubc** [comment]
Deleted for lack of followup/updates.
