### ISSUE TITLE
Yass AMI cannot be found in EC2 on AWS

### ISSUE THREAD

**Issue by alinaheukamp** [paninski-lab/yass#336]
Hi,

It seems like the AMI on AWS is not available worldwide, but instead it is region dependent. I tried finding it from my region (Europe) and couldn't find it.

When I switch to "US East (N. Virginia) us-east-1" I can find it.

Maybe this might be useful to add in the installation instructions in the wiki.

**Comment by catubc** [comment]
Hi 
Can you please confirm whether you resolved this issue?
Thanks,

**Comment by alinaheukamp** [comment]
Hi,

Sorry for the delay. The issue is still there. I think what you need to do is change the settings for the AMI so that it's accessible from anywhere.
It wasn't trivial to set it up for us - we needed to create a copy of the AMI and do several things that I don't remember anymore. So I think it would be the easiest it if was accessible from the beginning.
Thanks
