### ISSUE TITLE
demo notebook?

### ISSUE THREAD

**Issue by slinderman** [paninski-lab/yass#337]
Hi all, 

What's the easiest way to get started with YASS? Do you have a demo notebook with synthetic or (preferably) real data that walks through the various steps? If possible, I'd like to have my students play with YASS, or at least the core steps of the pipeline, in a "skills lab" for a course I'm developing.  What do you think?

Best,
Scott

**Comment by catubc** [comment]
Hey Scott
Yass is available as stand alone and AWS image. Also, yass is in the process of being pushed into the SpikeInterface project:

https://github.com/SpikeInterface

I recommend that you/your student learn how to use that tool - as it gives access to other spikesorters as well.  Yass should be integrated within a few weeks into that project and then can be used similarly to other tools.

If you have other questions, let us know.
Best
Cat
