### ISSUE TITLE
yass and tensorflow version.

### ISSUE THREAD

**Issue by samuelgarcia** [paninski-lab/yass#340]
I installed latest yass version with pip.

I get this `AttributeError: module 'tensorflow' has no attribute 'logging'`

logging seams to refer to very old version of tensorflow.

Which version of TF does yass need ?

**Comment by samuelgarcia** [comment]
I am lost here.
I am now trying to install yass from source. And now yass use troch and not tensorflow.


Note that I am trying this with the spikeinterface wrapper to make benchamark.


What is the best to test yass ?
 1. pip install yass-algorithm + tensorflow version XXXX ?
 2. install from source + torch ?

But:

1. do not work because
 ```AttributeError: module 'tensorflow' has no attribute 'logging'```
2. do not work because
  ```
Traceback (most recent call last):
  File "/home/samuel/.virtualenvs/py38/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm==2.0', 'console_scripts', 'yass')()
  File "/home/samuel/.virtualenvs/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/samuel/.virtualenvs/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/samuel/.virtualenvs/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/samuel/.virtualenvs/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/samuel/.virtualenvs/py38/lib/python3.8/site-packages/yass_algorithm-2.0-py3.8-linux-x86_64.egg/yass/command_line.py", line 13, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'
  ```

**Comment by samuelgarcia** [comment]
The anwser is here:
https://github.com/paninski-lab/yass/wiki/Installation-Local

**Comment by catubc** [comment]
Thanks for reading the wiki.  We are close to a pip-install version, will post that soon.

**Comment by samuelgarcia** [comment]
I still have problem for running yass.
I will investigate more.
install torch=1.2 with pip is no more possible.
Which version would you suggest ?

**Comment by catubc** [comment]
It's not clear what the issue is, torch 1.2 should always be available for python 3.7. We suggest starting over in a new environment with the correct version:
```

(yass_test) cat@cat-GF63-Thin-9SCX:~$ python --version
Python 3.7.0
(yass_test) cat@cat-GF63-Thin-9SCX:~$ pip install torch==1.2
Collecting torch==1.2
  Using cached torch-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (748.9 MB)
Collecting numpy
  Using cached numpy-1.20.1-cp37-cp37m-manylinux2010_x86_64.whl (15.3 MB)
Installing collected packages: numpy, torch
Successfully installed numpy-1.20.1 torch-1.2.0
(yass_test) cat@cat-GF63-Thin-9SCX:~$ 

```

If this still doesn't work, let us know.

**Comment by samuelgarcia** [comment]
I have python3.8 maybe that is the problem.
Anything that prevent yass to run on py38 ?

**Comment by catubc** [comment]
Please follow the instructions in the install wiki. We have not tested any other versions, and py38 is not compatible with earlier torch versions.

**Comment by samuelgarcia** [comment]
OK I see. I will investigate this.
