### ISSUE TITLE
cortical data

### ISSUE THREAD

**Issue by mishek-thapa** [paninski-lab/yass#345]
Any advice on using yass with cortical data? Do you have suggestions for which parameters to adjust for this context? I'm currently only getting about 5 units in a recording after training the neural net.

**Comment by catubc** [comment]
Hi Mishek
Yass should work relatively well on non-drift in-vivo recordings. So if the animals are anesthetized or not moving much. There's a yass with drift that we're working on , but will take a while longer.
The start parameters should be good, I'd use those until you find otherwise.

**Comment by mishek-thapa** [comment]
@catubc following up: These animals were pretty stable. However, I'm not sure we're getting appropriate number of units even with a trained neural net based on the results from other spike sorters. Here's the log file:

[yass.log](https://github.com/paninski-lab/yass/files/7182493/yass.log)
