### ISSUE TITLE
working example with multiple clusters

### ISSUE THREAD

**Issue by jsv13** [paninski-lab/yass#39]
Is there any  example where more than one cluster is detected per channel? would be nice to include some of the examples you used for your paper so that people can directly compare the clustering results with other methods.
Thanks!

**Comment by edublancas** [comment]
Hi, we are currently working on including a comprehensive example with a bigger dataset. Will update soon.

**Comment by jsv13** [comment]
sounds good!
Do you maybe have already  some documentation ready? E.g when I want to use larger datasets (5GB) I run into memory errors and I do not know what parameters to tune. Is it max_memory or sth else?

**Comment by edublancas** [comment]
Yes, docs are here: https://yass.readthedocs.io/en/latest/

Info about the configuration file: https://yass.readthedocs.io/en/latest/config.html

Can you share the error message you are getting, that will help us improve yass

**Comment by jsv13** [comment]
thanks for the links to the docs. I went through them, but some things are less well documented, e.g.

- selection of standard deviation for thresholding, constant or dynamically adjusted?
- masking_threshold parameters: what do they mean exactly?
- merge threshold parameters: what do they mean exactly?
- etc.

Regarding the **memory** error message it is the spike_sorting function and specifically the MFM ( see code below):

> /yass/MFM.pyc in calc_maskedData_mfm(self, score, mask, group)
>     173         z = mask[:, np.newaxis, np.newaxis, :] * scoreSq + \
>     174             (1 - mask)[:, np.newaxis, np.newaxis, :] * \
> --> 175             (np.eye(nfeature)[np.newaxis, :, :, np.newaxis])
>     176         eta = z - ySq
>     177 
> MemoryError: 

Hope this helps to trace the error.

**Comment by edublancas** [comment]
Thanks for the feeback, I will improve the documentation and report the memory error to the programmer who is working on the MFM part. Will keep you posted.

**Comment by edublancas** [comment]
Can you please provide some information on your dataset? (number of channels, size, etc.) as well as information about your machine? (GPU/CPU, amount of memory). Thanks.

**Comment by jsv13** [comment]
100 channels, 30kHz sampling rate, data files size: 1GB - 50GB.
The memory error I already get for file size of 1.3GB.

**Memory** : 16GB
**cpu info**

> Architecture:          x86_64
> CPU(s):                8
> Model name:            Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by edublancas** [comment]
@nd2506 can you take a look at this memory error? Can the new clustering method help here?

**Comment by nd2506** [comment]
@jsv13  Can you post the entire stack trace here?

**Comment by jsv13** [comment]
~/yass/test_yass2.py in <module>()
	 73         if len(score):
	 74             mp = Mainprocessor(cfg, score, spike_index_clear, spike_index_collision)
---> 75             spike_train_clear, spike_index_collision = mp.mainProcess()
	 76 
	 77             dc = Deconvolution(cfg, np.transpose(mp.templates, [1, 0, 2]),

~/local/lib/python2.7/site-packages/yass/mainprocess.pyc in mainProcess(self)
	158                 coreset_id_group = coreset_id_group - 1
	159                 n_coreset = 0
--> 160                 cluster_id = spikesort(score_group, mask_group, coreset_id_group, self.config)
	161                 print;print(sum((cluster_id>-1)));print
	162                 Time['s'] += (datetime.datetime.now()-_b).total_seconds()

~/local/lib/python2.7/site-packages/yass/MFM.pyc in spikesort(score, mask, group, param)
	979     # param.n_chan = np.sum(usedchan)
	980 
--> 981     maskedData = maskData(score, mask, group)
	982 
	983     vbParam = split_merge(maskedData, param)

~/local/lib/python2.7/site-packages/yass/MFM.pyc in init(self, *args)
	139         """
	140         if len(args) > 0:
--> 141             self.calc_maskedData_mfm(args[0], args[1], args[2])
	142 
	143     def calc_maskedData_mfm(self, score, mask, group):

~/local/lib/python2.7/site-packages/yass/MFM.pyc in calc_maskedData_mfm(self, score, mask, group)
	223         self.meanY = self.sumY / self.weight[:, np.newaxis, np.newaxis]
	224         self.meanYSq = self.sumYSq / \
--> 225             self.weight[:, np.newaxis, np.newaxis, np.newaxis]
	226         self.meanEta = self.sumEta / \
	227             self.weight[:, np.newaxis, np.newaxis, np.newaxis]

MemoryError: `

**Comment by edublancas** [comment]
@jsv13 Would you be able to share your data? That can help us spot the issue, we haven't experienced memory issues in that part of the code, it's hard for us to understand what's going on

**Comment by jsv13** [comment]
unfortunately this is not possible due to ownership issues.
Btw, which is the most latest version that actually works?
I just tried to install the latest stable version using

`pip install yass-algorithm`
and now I get 

> KeyError: 'clustering_method'

**Comment by edublancas** [comment]
I understand. Last version 0.6 works but we updated the `config.yaml` file since we added a new clustering method. https://yass.readthedocs.io/en/latest/config.html

**Comment by nd2506** [comment]
mask and group are the variables you pass into spikesort() . 

cluster_id = spikesort(score_group, mask_group, coreset_id_group, self.config)

Can you tell me their shapes?

**Comment by nd2506** [comment]
Also 2+3 doesn't work with threshold detection. Please use 3xn_channels with threshold detection.

**Comment by jsv13** [comment]
I was using version 0.3, so I thought this may be a problem. I now installed version 0.6, but I still get a memory error even for **1sec** file. I cannot use my previous python code, because the API has been changed, but I do use

> yass sort config_file.yaml

Could it be somehow related to the geometry file? The data has been acquired from a Utah array, where there shouldn't be an overlap of spikes recorded from different electrodes. The electrode spacing is 400μm.  Do you know what geometry file is best to use in this case? I use a file where all coordinates are zero.

The error I get is following:
>   File "/home/bin/yass", line 11, in <module>
	sys.exit(cli())
  File "/home/local/lib/python2.7/site-packages/click/core.py", line 722, in call
	return self.main(*args, **kwargs)
  File "/home/local/lib/python2.7/site-packages/click/core.py", line 697, in main
	rv = self.invoke(ctx)
  File "/home/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
	return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
	return ctx.invoke(self.callback, **ctx.params)
  File "/home/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
	return callback(*args, **kwargs)
  File "/home/local/lib/python2.7/site-packages/yass/command_line.py", line 59, in sort
	output_dir=output_dir, complete=complete)
  File "/home/local/lib/python2.7/site-packages/yass/command_line.py", line 102, in _run_pipeline
	output_directory=output_dir)
  File "/home/local/lib/python2.7/site-packages/yass/process/run.py", line 348, in run
	coreset_id_group, CONFIG)
  File "/home/local/lib/python2.7/site-packages/yass/mfm.py", line 973, in spikesort
	maskedData = maskData(score, mask, group)
  File "/home/local/lib/python2.7/site-packages/yass/mfm.py", line 78, in init
	self.calc_maskedData_mfm(args[0], args[1], args[2])
  File "/home/local/lib/python2.7/site-packages/yass/mfm.py", line 118, in calc_maskedData_mfm
	(np.eye(nfeature)[np.newaxis, :, :, np.newaxis])
MemoryError

**Comment by jinhyunglee** [comment]
Hi, yes. I think it is because of geometry.
To confirm, could you tell me the size of 'score' variable coming out of preprocess?

If they are far apart, I would suggest make a geometry file of [n_channels, 2] with random numbers.
and set spatial_radius to a very small number such that spatial_radius < smallest possible pairwise distance between channels.

**Comment by jsv13** [comment]
@jinhyunglee : yes, it is indeed the geometry! Now it works!

I used 
> yass sort config.yaml 

and not the API. Is there any documentation about the new API? The entries in yass.readthedocs.io are empty and the old code I used with version 0.3 is very slow and causes lots of errors.

Btw, since there is probably no overlap of spikes between the electrodes is there a way to speed up parts of yass? Is it sufficient to set spatial_radius < smallest possible  pairwise distance to avoid this clustering step altogether?

**Comment by edublancas** [comment]
@jsv13 thanks for letting us know about the docs, I just fixed them. There was a problem with the building process. Just be aware that we are still updating

**Comment by tdhawal1998** [comment]
@jsv13 , I am facing the same error. How did you get it to work exactly? What was the problem?

**Comment by edublancas** [comment]
@tdhawal1998 which is the problem you are getting? can you describe it in a new issue?
