### ISSUE TITLE
replacing .ckpt with .yaml  

### ISSUE THREAD

**Issue by ShenghaoWu** [paninski-lab/yass#41]
There is a potential problem when we replace the string 'ckpt' with 'yaml' when loading the parameters of the nn. For example, someone stores her nn_detector with the following path:  /examples/**ckpt**/nn_detector.ckpt, YASS will loads /examples/**yaml**/nn_detector.yaml for parameters and throws an error. Maybe we should look at '.ckpt' instead of 'ckpt' ?

**Comment by edublancas** [comment]
Thanks for pointing this out, I'll fix it
