### ISSUE TITLE
detection needs buffer

### ISSUE THREAD

**Issue by jinhyunglee** [paninski-lab/yass#96]
both threshold detection and neural net detector need buffer.

**Comment by jinhyunglee** [comment]
buffer added to neural net detector but not to threshold detector yet

**Comment by edublancas** [comment]
Same size, right?

**Comment by jinhyunglee** [comment]
yes

**Comment by jinhyunglee** [comment]
Did you add it? It seems like its there now.

**Comment by edublancas** [comment]
Oh yeah, I forgot that I added it. Closing the issue
