### ISSUE TITLE
new feature request: Batchprocessor

### ISSUE THREAD

**Issue by jinhyunglee** [paninski-lab/yass#97]
when applying a function batch-wise, 
I would like to have the number of the current batch, the batch_size, and the buffer size within the function.

**Comment by edublancas** [comment]
Just implemented this, check the docs:

https://yass.readthedocs.io/en/latest/api/batch.html#yass.batch.BatchProcessor.multi_channel_apply

I am not explicitly passing what you asked but something (I believe) cleaner, if the docs are not clear enough, let me know
